$axure.loadCurrentPage({
  "url":"news.html",
  "generationDate":new Date(1396931400195.26),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"309d815d2ea54d268a57f6ce8acfacf4",
    "type":"Axure:Page",
    "name":"News",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b55fe422ea2249169d20955a9bd5feb9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":25,
              "y":185},
            "size":{
              "width":150,
              "height":33},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"297c919fb2a043a5a726f228c996b127",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":25,
                  "y":185},
                "size":{
                  "width":150,
                  "height":33},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7affb086aa6b43af9b574a50c586afe5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":25,
              "y":765},
            "size":{
              "width":704,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fba325d0b79943fcbb0c95143dc306dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":25,
                  "y":765},
                "size":{
                  "width":704,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/news/u2.png"}},
{
          "id":"027159cb80874c28b20b8dfb789eaed3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":25,
              "y":185},
            "size":{
              "width":150,
              "height":33},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5bd5bfa9fb44bdc968195cc593223dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":25,
                  "y":185},
                "size":{
                  "width":150,
                  "height":33},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d8a4fa744e09434999cb985903e2114f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":25,
              "y":235},
            "size":{
              "width":373,
              "height":159},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82982b292ff447069ebd654acecebed8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":25,
                  "y":235},
                "size":{
                  "width":373,
                  "height":159},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/news/u6.png"}},
{
          "id":"818093638ae24192851bde2c2a536240",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":408,
              "y":404},
            "size":{
              "width":321,
              "height":326}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e2994545fe04c759e49363326f27455",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":408,
                  "y":404},
                "size":{
                  "width":321,
                  "height":326}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/news/u8.png"}},
{
          "id":"4113557319df4fccbe5c3a4d7fdce389",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":25,
              "y":404},
            "size":{
              "width":373,
              "height":326}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40cc172f19a844789f1589d205a21c95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":25,
                  "y":404},
                "size":{
                  "width":373,
                  "height":326}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/news/u10.png"}},
{
          "id":"c0ec9fbed62243c29645b5b3fea2d3d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":33,
              "y":242},
            "size":{
              "width":150,
              "height":22},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"623aeaae0fe844c4a655fa972777c16d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":33,
                  "y":242},
                "size":{
                  "width":150,
                  "height":22},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"faf3ec372a3b479696303bdeb5f058ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":33,
              "y":274},
            "size":{
              "width":321,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52d8bbc5301848c5bfe6e49adc200ad0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":33,
                  "y":274},
                "size":{
                  "width":321,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25d7807645d442d1b02ece595df68daf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":33,
              "y":306},
            "size":{
              "width":321,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf3ca5ace846469d8fbe0b3e5f2ffbfe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":33,
                  "y":306},
                "size":{
                  "width":321,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"151c7d52a577427abf2b9793444dfbaa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":33,
              "y":414},
            "size":{
              "width":150,
              "height":22},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"166f0b85c97c4461bda50db02a8c59ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":33,
                  "y":414},
                "size":{
                  "width":150,
                  "height":22},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"549d19f50abb480ba84a3ba69d60baa4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":25,
              "y":636},
            "size":{
              "width":339,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a3414639db94f978b68c669c98f8bde",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":25,
                  "y":636},
                "size":{
                  "width":339,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"06a736fd234f4c2ab8fdea79b4892b3a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":645},
            "size":{
              "width":339,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4283bd105b543469008421d6e2ccdf0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":645},
                "size":{
                  "width":339,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf90022e0ff94ae4aa5cc1dfb96b4f04",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":420,
              "y":414},
            "size":{
              "width":189,
              "height":22},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ceff9f251deb4f9a93ab42ce055abfad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":420,
                  "y":414},
                "size":{
                  "width":189,
                  "height":22},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"075b106ed4714ac784bfe86e53f9a1cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":456},
            "size":{
              "width":280,
              "height":192},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"702e18e74b0d46388e3854ece4cdac11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":456},
                "size":{
                  "width":280,
                  "height":192},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2cb46518af734cf4b3867c78f2136645",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":33,
              "y":446},
            "size":{
              "width":339,
              "height":264}},
          "adaptiveStyles":{
}},
{
          "id":"614d56ebb8c64249badbfb80ee17d883",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":408,
              "y":235},
            "size":{
              "width":321,
              "height":159}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d7002e8e1544e49a122f8e6daa4e8fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":408,
                  "y":235},
                "size":{
                  "width":321,
                  "height":159}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/news/u29.png"}},
{
          "id":"cb4b8650d32b4867b34e901c5d88e2f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":420,
              "y":245},
            "size":{
              "width":150,
              "height":22},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0320ef54b067471aac169d7ab36755ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":420,
                  "y":245},
                "size":{
                  "width":150,
                  "height":22},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ba2b80c5b3d4aa2801e803a7e483fe6",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":471.5,
              "y":277},
            "size":{
              "width":194,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Loop Labs in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"loop_labs.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"3442152a5ddf4ee592d98cac5d71503b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":471.5,
              "y":312},
            "size":{
              "width":194,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open LP Labs in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"lp_labs.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"da4f22b2d2cf40e78b772f1060c24b28",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":471.5,
              "y":347},
            "size":{
              "width":194,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Campus Maps in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"campus_maps.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"7f94cdb6b56c454aa334d84eb2eec3e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":13},
            "size":{
              "width":231,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c56c8e30fb6f410196e82e38dda1b29b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":13},
                "size":{
                  "width":231,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"e8703daebc494e5c96df5c81f089cd49",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":123},
            "size":{
              "width":195,
              "height":52},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72867a2c75ab4546848f809fd7612dba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":123},
                "size":{
                  "width":195,
                  "height":52},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open News in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"news.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"7071d94d47424ccaa4619ea3cdd40279",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":208,
              "y":123},
            "size":{
              "width":195,
              "height":52},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bedc325de6f14ec4b09537385c05c859",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":208,
                  "y":123},
                "size":{
                  "width":195,
                  "height":52},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 2",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Services in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"services.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"a0089248936a477fb481a9d70b1e8f41",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":403,
              "y":123},
            "size":{
              "width":195,
              "height":52},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9776e9073d3441f5833241f30d6cc344",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":403,
                  "y":123},
                "size":{
                  "width":195,
                  "height":52},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Student Activities in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"student_activities.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"9e29a6b01f724cf5acbd46af3e64a171",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":597,
              "y":123},
            "size":{
              "width":195,
              "height":52},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6902d499b0a84306a5c4aea9f31ef754",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":597,
                  "y":123},
                "size":{
                  "width":195,
                  "height":52},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Portfolio in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"portfolio.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"ba5fc5ecf9d54b128e5d707c2b8d59fc",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":583,
              "y":74},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"688628ca68c946a997ce22dcac896abe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":175,
              "y":109},
            "size":{
              "width":23,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b88291f27bfa418e8363b4e1725324be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":175,
                  "y":109},
                "size":{
                  "width":23,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC0000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u29.png"}},
{
          "id":"e146cbcfa6ab44fdb32396bf81c1f265",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":597,
              "y":13},
            "size":{
              "width":208,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac49bc70edcc447f8a43895d73fd5550",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":597,
                  "y":13},
                "size":{
                  "width":208,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "b55fe422ea2249169d20955a9bd5feb9":{
      "scriptId":"u0"},
    "297c919fb2a043a5a726f228c996b127":{
      "scriptId":"u1"},
    "7affb086aa6b43af9b574a50c586afe5":{
      "scriptId":"u2"},
    "fba325d0b79943fcbb0c95143dc306dc":{
      "scriptId":"u3"},
    "027159cb80874c28b20b8dfb789eaed3":{
      "scriptId":"u4"},
    "c5bd5bfa9fb44bdc968195cc593223dd":{
      "scriptId":"u5"},
    "d8a4fa744e09434999cb985903e2114f":{
      "scriptId":"u6"},
    "82982b292ff447069ebd654acecebed8":{
      "scriptId":"u7"},
    "818093638ae24192851bde2c2a536240":{
      "scriptId":"u8"},
    "1e2994545fe04c759e49363326f27455":{
      "scriptId":"u9"},
    "4113557319df4fccbe5c3a4d7fdce389":{
      "scriptId":"u10"},
    "40cc172f19a844789f1589d205a21c95":{
      "scriptId":"u11"},
    "c0ec9fbed62243c29645b5b3fea2d3d6":{
      "scriptId":"u12"},
    "623aeaae0fe844c4a655fa972777c16d":{
      "scriptId":"u13"},
    "faf3ec372a3b479696303bdeb5f058ee":{
      "scriptId":"u14"},
    "52d8bbc5301848c5bfe6e49adc200ad0":{
      "scriptId":"u15"},
    "25d7807645d442d1b02ece595df68daf":{
      "scriptId":"u16"},
    "cf3ca5ace846469d8fbe0b3e5f2ffbfe":{
      "scriptId":"u17"},
    "151c7d52a577427abf2b9793444dfbaa":{
      "scriptId":"u18"},
    "166f0b85c97c4461bda50db02a8c59ce":{
      "scriptId":"u19"},
    "549d19f50abb480ba84a3ba69d60baa4":{
      "scriptId":"u20"},
    "5a3414639db94f978b68c669c98f8bde":{
      "scriptId":"u21"},
    "06a736fd234f4c2ab8fdea79b4892b3a":{
      "scriptId":"u22"},
    "f4283bd105b543469008421d6e2ccdf0":{
      "scriptId":"u23"},
    "bf90022e0ff94ae4aa5cc1dfb96b4f04":{
      "scriptId":"u24"},
    "ceff9f251deb4f9a93ab42ce055abfad":{
      "scriptId":"u25"},
    "075b106ed4714ac784bfe86e53f9a1cf":{
      "scriptId":"u26"},
    "702e18e74b0d46388e3854ece4cdac11":{
      "scriptId":"u27"},
    "2cb46518af734cf4b3867c78f2136645":{
      "scriptId":"u28"},
    "614d56ebb8c64249badbfb80ee17d883":{
      "scriptId":"u29"},
    "1d7002e8e1544e49a122f8e6daa4e8fb":{
      "scriptId":"u30"},
    "cb4b8650d32b4867b34e901c5d88e2f1":{
      "scriptId":"u31"},
    "0320ef54b067471aac169d7ab36755ff":{
      "scriptId":"u32"},
    "0ba2b80c5b3d4aa2801e803a7e483fe6":{
      "scriptId":"u33"},
    "3442152a5ddf4ee592d98cac5d71503b":{
      "scriptId":"u34"},
    "da4f22b2d2cf40e78b772f1060c24b28":{
      "scriptId":"u35"},
    "7f94cdb6b56c454aa334d84eb2eec3e9":{
      "scriptId":"u36"},
    "c56c8e30fb6f410196e82e38dda1b29b":{
      "scriptId":"u37"},
    "e8703daebc494e5c96df5c81f089cd49":{
      "scriptId":"u38"},
    "72867a2c75ab4546848f809fd7612dba":{
      "scriptId":"u39"},
    "7071d94d47424ccaa4619ea3cdd40279":{
      "scriptId":"u40"},
    "bedc325de6f14ec4b09537385c05c859":{
      "scriptId":"u41"},
    "a0089248936a477fb481a9d70b1e8f41":{
      "scriptId":"u42"},
    "9776e9073d3441f5833241f30d6cc344":{
      "scriptId":"u43"},
    "9e29a6b01f724cf5acbd46af3e64a171":{
      "scriptId":"u44"},
    "6902d499b0a84306a5c4aea9f31ef754":{
      "scriptId":"u45"},
    "ba5fc5ecf9d54b128e5d707c2b8d59fc":{
      "scriptId":"u46"},
    "688628ca68c946a997ce22dcac896abe":{
      "scriptId":"u47"},
    "b88291f27bfa418e8363b4e1725324be":{
      "scriptId":"u48"},
    "e146cbcfa6ab44fdb32396bf81c1f265":{
      "scriptId":"u49"},
    "ac49bc70edcc447f8a43895d73fd5550":{
      "scriptId":"u50"}}});