$axure.loadCurrentPage({
  "url":"loop_labs.html",
  "generationDate":new Date(1397006830566.93),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"976cc7c25a0042c79cb4f134290aea50",
    "type":"Axure:Page",
    "name":"Loop labs",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3f501cee7be74e319b06b63c89dbb04e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":61,
              "y":29},
            "size":{
              "width":361,
              "height":555},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"659ab7b825e04fe59175d781ddadb942",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":61,
                  "y":29},
                "size":{
                  "width":361,
                  "height":555},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"3d4285633bca4d5ba870214644c60154",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":77,
              "y":68},
            "size":{
              "width":325,
              "height":429},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b0f5943a4db4c56a6357bd52b09ee21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":77,
                  "y":68},
                "size":{
                  "width":325,
                  "height":429},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lp_labs/u2.png"}},
{
          "id":"6c21057807b143699a452650f5fa2620",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":214,
              "y":516},
            "size":{
              "width":52,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d16945ae742f470487198288ec246eb6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":214,
                  "y":516},
                "size":{
                  "width":52,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"23f5a7dccf064f41b6057e44ed11164a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":77,
              "y":68},
            "size":{
              "width":325,
              "height":87}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7e557707ef948a79c2166784fd7cfed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":77,
                  "y":68},
                "size":{
                  "width":325,
                  "height":87}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lp_labs/u6.png"}},
{
          "id":"f13427d53c144c128e7efb5643e21746",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":327,
              "y":77},
            "size":{
              "width":69,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"a65dad37c6cb41f195f0daab8947e2e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":164,
              "y":122},
            "size":{
              "width":150,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bae14d25cec845f8bf6a9d32431794de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":164,
                  "y":122},
                "size":{
                  "width":150,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"12117e06b6644b879568d0ecde2ce8aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFF0099CC},
            "location":{
              "x":77,
              "y":165},
            "size":{
              "width":325,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a185330a7ed54521bd1118d37708354f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099CC},
                "location":{
                  "x":77,
                  "y":165},
                "size":{
                  "width":325,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open LP labs in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"lp_labs.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/lp_labs/u11.png"}},
{
          "id":"4dcda5cb4f924bebb6134d5530cc51a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":77,
              "y":198},
            "size":{
              "width":325,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"301f47765c874251912c6887c88a4c19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":77,
                  "y":198},
                "size":{
                  "width":325,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Loop labs in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"loop_labs.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/lp_labs/u64.png"}},
{
          "id":"f04478a0072a457e81a12ad4c60ea737",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":88,
              "y":231},
            "size":{
              "width":303,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e745990aa1645928d8a3c68f03d6731",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":88,
                  "y":231},
                "size":{
                  "width":303,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lp_labs/u13.png"}},
{
          "id":"c66fe5bf7ad3499295289c29b47b30ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":98,
              "y":236},
            "size":{
              "width":134,
              "height":13},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"506ba7449c3347cc9e3d2e4b55c94c6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":98,
                  "y":236},
                "size":{
                  "width":134,
                  "height":13},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"434395415a4441ddb9c871b584daa13f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":239},
            "size":{
              "width":81,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f660dff096e45a1b1ff9b7052f13fac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":239},
                "size":{
                  "width":81,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lp_labs/u17.png"}},
{
          "id":"832002418ff441f7b74dcc1cb60a16b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00FF00},
            "location":{
              "x":240,
              "y":239},
            "size":{
              "width":55,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74ed0b2e31f440478e12d49d0076d50b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FF00},
                "location":{
                  "x":240,
                  "y":239},
                "size":{
                  "width":55,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lp_labs/u19.png"}},
{
          "id":"c06429dada9d4bc487d99c70e13c64e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":266,
              "y":239},
            "size":{
              "width":30,
              "height":13},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b907f1f47a534ae1a843f3e897e84cdf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":266,
                  "y":239},
                "size":{
                  "width":30,
                  "height":13},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9e9b3ebafe17495e991a83f550f3f4ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":88,
              "y":270},
            "size":{
              "width":303,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87b16fa30b914fb097b452aa40af5c29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":88,
                  "y":270},
                "size":{
                  "width":303,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lp_labs/u13.png"}},
{
          "id":"3328498a36584ab0ba3d17b1628a9cd9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":98,
              "y":275},
            "size":{
              "width":134,
              "height":13},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3340e1b8379e4813b7171fb930dbd700",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":98,
                  "y":275},
                "size":{
                  "width":134,
                  "height":13},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1eed0bab9b264471ad4958f00e5fb845",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":278},
            "size":{
              "width":81,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1de7a659395c467b9ccff6ed63f734aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":278},
                "size":{
                  "width":81,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lp_labs/u17.png"}},
{
          "id":"ee5c020d4b424ec6a0f6d2ad7d60c788",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00FF00},
            "location":{
              "x":240,
              "y":278},
            "size":{
              "width":55,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ec583842bcc441281545bf07e2b8511",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FF00},
                "location":{
                  "x":240,
                  "y":278},
                "size":{
                  "width":55,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lp_labs/u19.png"}},
{
          "id":"25f939a4f4c64134b020743d570faccd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":266,
              "y":278},
            "size":{
              "width":30,
              "height":13},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f108ea8a09384bb99e2c4df2f77c1b14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":266,
                  "y":278},
                "size":{
                  "width":30,
                  "height":13},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"475f94b70f584170a1de70450e450edc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":88,
              "y":309},
            "size":{
              "width":303,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b74ce30667484921afdb87cccfedd42f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":88,
                  "y":309},
                "size":{
                  "width":303,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lp_labs/u13.png"}},
{
          "id":"f171c9bd635d4eafa8d64e7f3ed807e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":98,
              "y":314},
            "size":{
              "width":134,
              "height":13},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"831d66dec7684095856cf39d172ef49e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":98,
                  "y":314},
                "size":{
                  "width":134,
                  "height":13},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd717b5046ff4d4ba016f28eefe3ffe8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":317},
            "size":{
              "width":81,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d37b89db92d446a84007b0b78d81104",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":317},
                "size":{
                  "width":81,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lp_labs/u17.png"}},
{
          "id":"024e9d9f83a84ce7989eb248593d5cf5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00FF00},
            "location":{
              "x":240,
              "y":317},
            "size":{
              "width":55,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ce153a8a84340d4b8ccca59513daedc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FF00},
                "location":{
                  "x":240,
                  "y":317},
                "size":{
                  "width":55,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lp_labs/u19.png"}},
{
          "id":"acae1f5e985f456f9297353cd726e4f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":266,
              "y":317},
            "size":{
              "width":30,
              "height":13},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf3e919082e04630b672c231ebe16187",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":266,
                  "y":317},
                "size":{
                  "width":30,
                  "height":13},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"14a4663692814c1d9d5183e61c9b76f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":88,
              "y":348},
            "size":{
              "width":303,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ba2ffbd814745318b1afb0bdff5dc61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":88,
                  "y":348},
                "size":{
                  "width":303,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lp_labs/u13.png"}},
{
          "id":"1d2d879575ba4ad584923eeba6c74fb5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":98,
              "y":353},
            "size":{
              "width":134,
              "height":13},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93e820ec06974cb1b63ed73cd652a9f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":98,
                  "y":353},
                "size":{
                  "width":134,
                  "height":13},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac01f87a46814b569b1d23baeb04dfdb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":356},
            "size":{
              "width":81,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c55c89525beb4583897bf78d25e6b310",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":356},
                "size":{
                  "width":81,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lp_labs/u17.png"}},
{
          "id":"37772b52233245eda7f4f27a50c461a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00FF00},
            "location":{
              "x":240,
              "y":356},
            "size":{
              "width":55,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb61de3971df40388eff05d7b12f0ec0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FF00},
                "location":{
                  "x":240,
                  "y":356},
                "size":{
                  "width":55,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lp_labs/u19.png"}},
{
          "id":"5b740475c09f4f42b396c835a28a7abf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":266,
              "y":356},
            "size":{
              "width":30,
              "height":13},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e1da04f791148daa4d8b20365178834",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":266,
                  "y":356},
                "size":{
                  "width":30,
                  "height":13},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"af632055a1c94d72b55eeb48f8c98a9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":88,
              "y":387},
            "size":{
              "width":303,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9bdc9bb9a6764988846c1d235e18d437",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":88,
                  "y":387},
                "size":{
                  "width":303,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lp_labs/u13.png"}},
{
          "id":"b3fbccc5e7c046f68847818ef2bac2df",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":98,
              "y":392},
            "size":{
              "width":134,
              "height":13},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb17e097de624f978e0c466b47b9942f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":98,
                  "y":392},
                "size":{
                  "width":134,
                  "height":13},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c42980ab96b46328723b2c89143fdb6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":395},
            "size":{
              "width":81,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abc5595248e648ecbf3c4cc87db6faed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":395},
                "size":{
                  "width":81,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lp_labs/u17.png"}},
{
          "id":"ea07337e2d6747ca957cc316b4fa502c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00FF00},
            "location":{
              "x":240,
              "y":395},
            "size":{
              "width":55,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a02d7380f414958b919b09569e51bf5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FF00},
                "location":{
                  "x":240,
                  "y":395},
                "size":{
                  "width":55,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lp_labs/u19.png"}},
{
          "id":"84b529a0acfb49378c671b8371635768",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":266,
              "y":395},
            "size":{
              "width":30,
              "height":13},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"575f60b7562a4929ba79c4d413f8c811",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":266,
                  "y":395},
                "size":{
                  "width":30,
                  "height":13},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ef79347485454f45a217db26a7858c17",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":81,
              "y":77},
            "size":{
              "width":55,
              "height":24},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb9ee83149b04eb486747b14dccca1de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":81,
                  "y":77},
                "size":{
                  "width":55,
                  "height":24},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/lp_labs/u66.png"}},
{
          "id":"5d8bceb2cccd4c38bad35ce9b7206331",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":146,
              "y":77},
            "size":{
              "width":69,
              "height":22}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"12bcd74728534ca88df5aee4622e3d1b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":353,
              "y":236},
            "size":{
              "width":32,
              "height":21}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Details in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"details.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"df11e56b6fcf461095392f8ba3f8d99d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":353,
              "y":276},
            "size":{
              "width":32,
              "height":21}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Details in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"details.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"a572f6af391841f7b14970d8defccb50",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":353,
              "y":313},
            "size":{
              "width":32,
              "height":21}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Details in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"details.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"d562a1e62fc640a79e84849ca622bd6b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":353,
              "y":352},
            "size":{
              "width":32,
              "height":21}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Details in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"details.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"1ff258b2e31a4047815d9a7a29e5cb4d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":353,
              "y":390.5},
            "size":{
              "width":32,
              "height":21}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Details in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"details.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "3f501cee7be74e319b06b63c89dbb04e":{
      "scriptId":"u0"},
    "659ab7b825e04fe59175d781ddadb942":{
      "scriptId":"u1"},
    "3d4285633bca4d5ba870214644c60154":{
      "scriptId":"u2"},
    "7b0f5943a4db4c56a6357bd52b09ee21":{
      "scriptId":"u3"},
    "6c21057807b143699a452650f5fa2620":{
      "scriptId":"u4"},
    "d16945ae742f470487198288ec246eb6":{
      "scriptId":"u5"},
    "23f5a7dccf064f41b6057e44ed11164a":{
      "scriptId":"u6"},
    "e7e557707ef948a79c2166784fd7cfed":{
      "scriptId":"u7"},
    "f13427d53c144c128e7efb5643e21746":{
      "scriptId":"u8"},
    "a65dad37c6cb41f195f0daab8947e2e3":{
      "scriptId":"u9"},
    "bae14d25cec845f8bf6a9d32431794de":{
      "scriptId":"u10"},
    "12117e06b6644b879568d0ecde2ce8aa":{
      "scriptId":"u11"},
    "a185330a7ed54521bd1118d37708354f":{
      "scriptId":"u12"},
    "4dcda5cb4f924bebb6134d5530cc51a3":{
      "scriptId":"u13"},
    "301f47765c874251912c6887c88a4c19":{
      "scriptId":"u14"},
    "f04478a0072a457e81a12ad4c60ea737":{
      "scriptId":"u15"},
    "6e745990aa1645928d8a3c68f03d6731":{
      "scriptId":"u16"},
    "c66fe5bf7ad3499295289c29b47b30ca":{
      "scriptId":"u17"},
    "506ba7449c3347cc9e3d2e4b55c94c6b":{
      "scriptId":"u18"},
    "434395415a4441ddb9c871b584daa13f":{
      "scriptId":"u19"},
    "5f660dff096e45a1b1ff9b7052f13fac":{
      "scriptId":"u20"},
    "832002418ff441f7b74dcc1cb60a16b2":{
      "scriptId":"u21"},
    "74ed0b2e31f440478e12d49d0076d50b":{
      "scriptId":"u22"},
    "c06429dada9d4bc487d99c70e13c64e2":{
      "scriptId":"u23"},
    "b907f1f47a534ae1a843f3e897e84cdf":{
      "scriptId":"u24"},
    "9e9b3ebafe17495e991a83f550f3f4ad":{
      "scriptId":"u25"},
    "87b16fa30b914fb097b452aa40af5c29":{
      "scriptId":"u26"},
    "3328498a36584ab0ba3d17b1628a9cd9":{
      "scriptId":"u27"},
    "3340e1b8379e4813b7171fb930dbd700":{
      "scriptId":"u28"},
    "1eed0bab9b264471ad4958f00e5fb845":{
      "scriptId":"u29"},
    "1de7a659395c467b9ccff6ed63f734aa":{
      "scriptId":"u30"},
    "ee5c020d4b424ec6a0f6d2ad7d60c788":{
      "scriptId":"u31"},
    "6ec583842bcc441281545bf07e2b8511":{
      "scriptId":"u32"},
    "25f939a4f4c64134b020743d570faccd":{
      "scriptId":"u33"},
    "f108ea8a09384bb99e2c4df2f77c1b14":{
      "scriptId":"u34"},
    "475f94b70f584170a1de70450e450edc":{
      "scriptId":"u35"},
    "b74ce30667484921afdb87cccfedd42f":{
      "scriptId":"u36"},
    "f171c9bd635d4eafa8d64e7f3ed807e4":{
      "scriptId":"u37"},
    "831d66dec7684095856cf39d172ef49e":{
      "scriptId":"u38"},
    "dd717b5046ff4d4ba016f28eefe3ffe8":{
      "scriptId":"u39"},
    "0d37b89db92d446a84007b0b78d81104":{
      "scriptId":"u40"},
    "024e9d9f83a84ce7989eb248593d5cf5":{
      "scriptId":"u41"},
    "6ce153a8a84340d4b8ccca59513daedc":{
      "scriptId":"u42"},
    "acae1f5e985f456f9297353cd726e4f3":{
      "scriptId":"u43"},
    "bf3e919082e04630b672c231ebe16187":{
      "scriptId":"u44"},
    "14a4663692814c1d9d5183e61c9b76f1":{
      "scriptId":"u45"},
    "3ba2ffbd814745318b1afb0bdff5dc61":{
      "scriptId":"u46"},
    "1d2d879575ba4ad584923eeba6c74fb5":{
      "scriptId":"u47"},
    "93e820ec06974cb1b63ed73cd652a9f9":{
      "scriptId":"u48"},
    "ac01f87a46814b569b1d23baeb04dfdb":{
      "scriptId":"u49"},
    "c55c89525beb4583897bf78d25e6b310":{
      "scriptId":"u50"},
    "37772b52233245eda7f4f27a50c461a2":{
      "scriptId":"u51"},
    "eb61de3971df40388eff05d7b12f0ec0":{
      "scriptId":"u52"},
    "5b740475c09f4f42b396c835a28a7abf":{
      "scriptId":"u53"},
    "7e1da04f791148daa4d8b20365178834":{
      "scriptId":"u54"},
    "af632055a1c94d72b55eeb48f8c98a9f":{
      "scriptId":"u55"},
    "9bdc9bb9a6764988846c1d235e18d437":{
      "scriptId":"u56"},
    "b3fbccc5e7c046f68847818ef2bac2df":{
      "scriptId":"u57"},
    "cb17e097de624f978e0c466b47b9942f":{
      "scriptId":"u58"},
    "0c42980ab96b46328723b2c89143fdb6":{
      "scriptId":"u59"},
    "abc5595248e648ecbf3c4cc87db6faed":{
      "scriptId":"u60"},
    "ea07337e2d6747ca957cc316b4fa502c":{
      "scriptId":"u61"},
    "8a02d7380f414958b919b09569e51bf5":{
      "scriptId":"u62"},
    "84b529a0acfb49378c671b8371635768":{
      "scriptId":"u63"},
    "575f60b7562a4929ba79c4d413f8c811":{
      "scriptId":"u64"},
    "ef79347485454f45a217db26a7858c17":{
      "scriptId":"u65"},
    "bb9ee83149b04eb486747b14dccca1de":{
      "scriptId":"u66"},
    "5d8bceb2cccd4c38bad35ce9b7206331":{
      "scriptId":"u67"},
    "12bcd74728534ca88df5aee4622e3d1b":{
      "scriptId":"u68"},
    "df11e56b6fcf461095392f8ba3f8d99d":{
      "scriptId":"u69"},
    "a572f6af391841f7b14970d8defccb50":{
      "scriptId":"u70"},
    "d562a1e62fc640a79e84849ca622bd6b":{
      "scriptId":"u71"},
    "1ff258b2e31a4047815d9a7a29e5cb4d":{
      "scriptId":"u72"}}});