excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://burgere.github.io
title: Eric Burger
email: eric.burger@comcast.net
author: Eric Burger
description: Fun with Making Things
paginate: 3
google_analytics: 