$axure.loadCurrentPage({
  "url":"new_doc_page.html",
  "generationDate":new Date(1396931402109.37),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9f5ef8e6262846828ef9043bff071ef7",
    "type":"Axure:Page",
    "name":"New Doc Page",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"375cde8bd23a4960ba3711c54e5cbea6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":597,
              "y":13},
            "size":{
              "width":208,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"163b29f4ef7d4156857be7f36253409d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":597,
                  "y":13},
                "size":{
                  "width":208,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2272568c4e25466eb6e64e44465ee4c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":13},
            "size":{
              "width":231,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"609eaca7821f487b90dd33f303beb2ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":13},
                "size":{
                  "width":231,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"485d57e5c9a449ea8bb2400f79c507b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":123},
            "size":{
              "width":195,
              "height":52},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4c680a83ad34c65a6b4d61b715f3ae1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":123},
                "size":{
                  "width":195,
                  "height":52},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open News in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"news.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"df20c1e1fc9f4783b5f2028dd41d5c33",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":208,
              "y":123},
            "size":{
              "width":195,
              "height":52},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e5575c0d8824960819b7d1c38151fe2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":208,
                  "y":123},
                "size":{
                  "width":195,
                  "height":52},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 2",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Services in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"services.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"41f385bfd36742e48d4e9669ff189a71",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":403,
              "y":123},
            "size":{
              "width":195,
              "height":52},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"191b18a65fea4811a2560f20d19da248",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":403,
                  "y":123},
                "size":{
                  "width":195,
                  "height":52},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Student Activities in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"student_activities.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"fa9c171af4cc4f529077a5e7aaa5a57a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":597,
              "y":123},
            "size":{
              "width":195,
              "height":52},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab0c6ff5e843458e91363170607b9320",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":597,
                  "y":123},
                "size":{
                  "width":195,
                  "height":52},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Portfolio in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"portfolio.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"3d949a9d5404431bbe566595fda5ec71",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":583,
              "y":74},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"22aaf7305abe4eab845cb2a0d955d150",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":175,
              "y":109},
            "size":{
              "width":23,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"088071ad183b44fd8c57f761c7886878",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":175,
                  "y":109},
                "size":{
                  "width":23,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC0000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u29.png"}},
{
          "id":"def84eaee6624f7ab0cf0a240ab784d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":185},
            "size":{
              "width":425,
              "height":442}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ef5187a0b12431e97ccbe0ebbe9bf86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":185},
                "size":{
                  "width":425,
                  "height":442}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/document_page/u15.png"}},
{
          "id":"4def92dc32d1474fb3865bdc914f9b63",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":324,
              "y":195},
            "size":{
              "width":122,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"fba9c420d0f34fe9b49cbb62d5ba05a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":295},
            "size":{
              "width":230,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d185da0d982c4ecb880adecf95145140",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":295},
                "size":{
                  "width":230,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9dc1f94eff7c444bb3674b9be3b48577",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":92,
              "y":347},
            "size":{
              "width":339,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44726370d5bf48fc92f3f4f0aff2a70b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":92,
                  "y":347},
                "size":{
                  "width":339,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"24c82433fe044147867d167436e10be6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":363},
            "size":{
              "width":394,
              "height":256},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9debf3d6539d4333a10c37efcfd7ea18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":363},
                "size":{
                  "width":394,
                  "height":256},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b177ab31708c432291ea07e67b8b9d4a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":637},
            "size":{
              "width":772,
              "height":119}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7deaf94fa0304dcfacac1925d85bd240",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":637},
                "size":{
                  "width":772,
                  "height":119}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/document_page/u24.png"}},
{
          "id":"cba0b95350ea4c4692c98cf1ec27a9a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":501,
              "y":195},
            "size":{
              "width":291,
              "height":223}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"370a41f9549b4572a87a7333610bfaab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":501,
                  "y":195},
                "size":{
                  "width":291,
                  "height":223}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/document_page/u26.png"}},
{
          "id":"5359c10b1c2a47ffaeb06a6bc0835d0a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":643},
            "size":{
              "width":105,
              "height":83},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddb88d3ee0984ad490ac8a6253ae2bfb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":643},
                "size":{
                  "width":105,
                  "height":83},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"4b974be21a5148deafa5424ece99f51c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":162,
              "y":643},
            "size":{
              "width":105,
              "height":83},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2edf53beb85d444a89da0d066b640d78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":162,
                  "y":643},
                "size":{
                  "width":105,
                  "height":83},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"729222c199e140378532c2564a2c2481",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":285,
              "y":643},
            "size":{
              "width":105,
              "height":83},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df7b6028aff24a7a887c4b082cd65b09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":285,
                  "y":643},
                "size":{
                  "width":105,
                  "height":83},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"bcc5cc3bd72040cdb1ff4411f2829280",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0099CC},
            "location":{
              "x":501,
              "y":195},
            "size":{
              "width":291,
              "height":82},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0066CC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dff91b39d42c4722be9dcb744e708940",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099CC},
                "location":{
                  "x":501,
                  "y":195},
                "size":{
                  "width":291,
                  "height":82},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0066CC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/document_page/u34.png"}},
{
          "id":"7f50c405dc8d41fcb411f80cceda53c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":525,
              "y":209},
            "size":{
              "width":104,
              "height":22},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb52a3e6d3464199a666d5e6232489a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":525,
                  "y":209},
                "size":{
                  "width":104,
                  "height":22},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"36737c9dd5f14b1cbd86c4156d4ad0b6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":713,
              "y":203},
            "size":{
              "width":50,
              "height":50},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"556fd761ede14c25ab9de7ba60e14894",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":713,
                  "y":203},
                "size":{
                  "width":50,
                  "height":50},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"0a13e9d285c0422c9cfb4a9d2558c883",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":618},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac645aeb186543d28ea46f1f2c37ac59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":618},
                "size":{
                  "width":100,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/document_page/u40.png"}},
{
          "id":"dac58773fa4b42f5918ecd2553898706",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":713,
              "y":253},
            "size":{
              "width":58,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddc72934465c402ead6c9cb6343bb686",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":713,
                  "y":253},
                "size":{
                  "width":58,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6aea3353897449fdb0e1474a0e79fce3",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":519,
              "y":287},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"d112786f929c4d6dbde016bcb2cfa0db",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":519,
              "y":322},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"871e60d02dc6468e925ea1bdd11519b6",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":519,
              "y":357},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"3955a09992fd45578ba125c31c49e57e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":642,
              "y":292},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84a64cd9d47f4333b9ec87688d81e83d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":642,
                  "y":292},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3c2505d007044faf840276ce1866b803",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":642,
              "y":318},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f44447fbba94d8aa470e39d9f118fa1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":642,
                  "y":318},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cefa02aa20154857a54a7f6858d47361",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":42,
              "y":796},
            "size":{
              "width":150,
              "height":22},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"807e78f9453c481a97e68ff49493369d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":42,
                  "y":796},
                "size":{
                  "width":150,
                  "height":22},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"04d2c73384fd4fc1b77c8ef1660a4237",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":828},
            "size":{
              "width":729,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/document_page/u53_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "375cde8bd23a4960ba3711c54e5cbea6":{
      "scriptId":"u0"},
    "163b29f4ef7d4156857be7f36253409d":{
      "scriptId":"u1"},
    "2272568c4e25466eb6e64e44465ee4c9":{
      "scriptId":"u2"},
    "609eaca7821f487b90dd33f303beb2ee":{
      "scriptId":"u3"},
    "485d57e5c9a449ea8bb2400f79c507b5":{
      "scriptId":"u4"},
    "d4c680a83ad34c65a6b4d61b715f3ae1":{
      "scriptId":"u5"},
    "df20c1e1fc9f4783b5f2028dd41d5c33":{
      "scriptId":"u6"},
    "4e5575c0d8824960819b7d1c38151fe2":{
      "scriptId":"u7"},
    "41f385bfd36742e48d4e9669ff189a71":{
      "scriptId":"u8"},
    "191b18a65fea4811a2560f20d19da248":{
      "scriptId":"u9"},
    "fa9c171af4cc4f529077a5e7aaa5a57a":{
      "scriptId":"u10"},
    "ab0c6ff5e843458e91363170607b9320":{
      "scriptId":"u11"},
    "3d949a9d5404431bbe566595fda5ec71":{
      "scriptId":"u12"},
    "22aaf7305abe4eab845cb2a0d955d150":{
      "scriptId":"u13"},
    "088071ad183b44fd8c57f761c7886878":{
      "scriptId":"u14"},
    "def84eaee6624f7ab0cf0a240ab784d6":{
      "scriptId":"u15"},
    "6ef5187a0b12431e97ccbe0ebbe9bf86":{
      "scriptId":"u16"},
    "4def92dc32d1474fb3865bdc914f9b63":{
      "scriptId":"u17"},
    "fba9c420d0f34fe9b49cbb62d5ba05a7":{
      "scriptId":"u18"},
    "d185da0d982c4ecb880adecf95145140":{
      "scriptId":"u19"},
    "9dc1f94eff7c444bb3674b9be3b48577":{
      "scriptId":"u20"},
    "44726370d5bf48fc92f3f4f0aff2a70b":{
      "scriptId":"u21"},
    "24c82433fe044147867d167436e10be6":{
      "scriptId":"u22"},
    "9debf3d6539d4333a10c37efcfd7ea18":{
      "scriptId":"u23"},
    "b177ab31708c432291ea07e67b8b9d4a":{
      "scriptId":"u24"},
    "7deaf94fa0304dcfacac1925d85bd240":{
      "scriptId":"u25"},
    "cba0b95350ea4c4692c98cf1ec27a9a5":{
      "scriptId":"u26"},
    "370a41f9549b4572a87a7333610bfaab":{
      "scriptId":"u27"},
    "5359c10b1c2a47ffaeb06a6bc0835d0a":{
      "scriptId":"u28"},
    "ddb88d3ee0984ad490ac8a6253ae2bfb":{
      "scriptId":"u29"},
    "4b974be21a5148deafa5424ece99f51c":{
      "scriptId":"u30"},
    "2edf53beb85d444a89da0d066b640d78":{
      "scriptId":"u31"},
    "729222c199e140378532c2564a2c2481":{
      "scriptId":"u32"},
    "df7b6028aff24a7a887c4b082cd65b09":{
      "scriptId":"u33"},
    "bcc5cc3bd72040cdb1ff4411f2829280":{
      "scriptId":"u34"},
    "dff91b39d42c4722be9dcb744e708940":{
      "scriptId":"u35"},
    "7f50c405dc8d41fcb411f80cceda53c1":{
      "scriptId":"u36"},
    "bb52a3e6d3464199a666d5e6232489a0":{
      "scriptId":"u37"},
    "36737c9dd5f14b1cbd86c4156d4ad0b6":{
      "scriptId":"u38"},
    "556fd761ede14c25ab9de7ba60e14894":{
      "scriptId":"u39"},
    "0a13e9d285c0422c9cfb4a9d2558c883":{
      "scriptId":"u40"},
    "ac645aeb186543d28ea46f1f2c37ac59":{
      "scriptId":"u41"},
    "dac58773fa4b42f5918ecd2553898706":{
      "scriptId":"u42"},
    "ddc72934465c402ead6c9cb6343bb686":{
      "scriptId":"u43"},
    "6aea3353897449fdb0e1474a0e79fce3":{
      "scriptId":"u44"},
    "d112786f929c4d6dbde016bcb2cfa0db":{
      "scriptId":"u45"},
    "871e60d02dc6468e925ea1bdd11519b6":{
      "scriptId":"u46"},
    "3955a09992fd45578ba125c31c49e57e":{
      "scriptId":"u47"},
    "84a64cd9d47f4333b9ec87688d81e83d":{
      "scriptId":"u48"},
    "3c2505d007044faf840276ce1866b803":{
      "scriptId":"u49"},
    "7f44447fbba94d8aa470e39d9f118fa1":{
      "scriptId":"u50"},
    "cefa02aa20154857a54a7f6858d47361":{
      "scriptId":"u51"},
    "807e78f9453c481a97e68ff49493369d":{
      "scriptId":"u52"},
    "04d2c73384fd4fc1b77c8ef1660a4237":{
      "scriptId":"u53"}}});