$axure.loadCurrentPage({
  "url":"uploading.html",
  "generationDate":new Date(1396931401860.36),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b1273acf11fd475ba5c0cde30050ed2f",
    "type":"Axure:Page",
    "name":"Uploading",
    "notes":{
      "Default":"<p><span>Click the loading bar for a transition to the document page.</span></p>"},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"787cdbb863f04f9e98ae410b455befdb",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":524,
              "y":200},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Upload a File in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"upload_a_file.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"1e824d852ff1408389667790ac517fbb",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":273,
              "y":196.5},
            "size":{
              "width":180,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"50a02e0cd53d42b1ad0e68ff683f0ab1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":269},
            "size":{
              "width":271,
              "height":175}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67dfd745a1d8482b83e4c14f3e8d29f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":269},
                "size":{
                  "width":271,
                  "height":175}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/portfolio/u2.png"}},
{
          "id":"5dc87becc571486fafb491d550a41f0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":316,
              "y":269},
            "size":{
              "width":338,
              "height":175}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa4bfcb5ff5649e7a4ae1ded3c96540d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":316,
                  "y":269},
                "size":{
                  "width":338,
                  "height":175}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/portfolio/u4.png"}},
{
          "id":"264007395c1544ae8556955e05d5186d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":454},
            "size":{
              "width":628,
              "height":261}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6f99e81f5714254a4bf48480207fd78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":454},
                "size":{
                  "width":628,
                  "height":261}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/portfolio/u6.png"}},
{
          "id":"95e21bbceee947b4b99cafeb4d68f9c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":725},
            "size":{
              "width":338,
              "height":175}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2cf422a0ab644ebcbf9fb10e2b1ab85b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":725},
                "size":{
                  "width":338,
                  "height":175}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/portfolio/u4.png"}},
{
          "id":"18e4689e63d34234afbe7a453cfbaa25",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":725},
            "size":{
              "width":274,
              "height":175}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2dd3bd8a7f52464380a23ab49bf44527",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":725},
                "size":{
                  "width":274,
                  "height":175}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/portfolio/u10.png"}},
{
          "id":"79b2c45c3c2d4eeea819f50da60bf7f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":910},
            "size":{
              "width":628,
              "height":57}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c63d56901b342d5bfb789fd45202057",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":910},
                "size":{
                  "width":628,
                  "height":57}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/portfolio/u12.png"}},
{
          "id":"39b3f4c062934f1f8f930bbf56117062",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":597,
              "y":13},
            "size":{
              "width":208,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d334c565081648b399986ce58bf3d7ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":597,
                  "y":13},
                "size":{
                  "width":208,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cda4a4c3882e4b56b8b5ea8b08810fe3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":45,
              "y":200},
            "size":{
              "width":176,
              "height":25},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc54f68880f647eda6580b8c58ef02ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":45,
                  "y":200},
                "size":{
                  "width":176,
                  "height":25},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/portfolio/u16.png"}},
{
          "id":"22d570c91c48411caaaea742770189e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":13},
            "size":{
              "width":231,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"338e6cbfba7e4f29b407e01932edfcfb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":13},
                "size":{
                  "width":231,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"79d31a6134db419f855c90a47ecb19f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":123},
            "size":{
              "width":195,
              "height":52},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"651a5efd145941cf8c3f4f5e2b0a7d9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":123},
                "size":{
                  "width":195,
                  "height":52},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open News in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"news.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"38cdbbfea5af4df6bad98dd089a2cf73",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":208,
              "y":123},
            "size":{
              "width":195,
              "height":52},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be21dd2ae41545678ff97178715d5c1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":208,
                  "y":123},
                "size":{
                  "width":195,
                  "height":52},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show/Hide Widget",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"bf2136bf168842c3a5cb7fdc39b63b2f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":403,
              "y":123},
            "size":{
              "width":195,
              "height":52},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b75f71ab7254cada2c0fc121d878215",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":403,
                  "y":123},
                "size":{
                  "width":195,
                  "height":52},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Student Activities in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"student_activities.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"43b1fa7c78bf422e9484777b941ae5b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":597,
              "y":123},
            "size":{
              "width":195,
              "height":52},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"229df1222d2248fabdec68e7cda98db6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":597,
                  "y":123},
                "size":{
                  "width":195,
                  "height":52},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Portfolio in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"portfolio.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"976f2e1f7a5b4a7082317f991d54a29a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":583,
              "y":74},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8c6b897ac9474fffbb2e6425674b9319",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":175,
              "y":109},
            "size":{
              "width":23,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddef09a070664640a639318f03109da6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":175,
                  "y":109},
                "size":{
                  "width":23,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC0000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u29.png"}},
{
          "id":"666c91db99664f8892016233f6af8d8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":94,
              "y":185},
            "size":{
              "width":538,
              "height":143}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"146c6dcc64eb4373b24a249d806c4799",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":94,
                  "y":185},
                "size":{
                  "width":538,
                  "height":143}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/uploading/u31.png"}},
{
          "id":"488c23682c134dc683db9d89ce31f7a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":320,
              "y":200},
            "size":{
              "width":86,
              "height":22},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a896df8302342a29ea9991e3ec2c347",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":320,
                  "y":200},
                "size":{
                  "width":86,
                  "height":22},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"31674f20a20d4000b9328dcbcabc0291",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":128,
              "y":240},
            "size":{
              "width":470,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ea10db28378452bb9cbb674ed41fafc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":128,
                  "y":240},
                "size":{
                  "width":470,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/uploading/u35.png"}},
{
          "id":"fde0caf7ca9e41b6adf6cab6a1cc91c9",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":288},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Upload a File in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"upload_a_file.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"f0e3c9f0a06342a6a9024da6f29c1e7b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00FF33},
            "location":{
              "x":128,
              "y":240},
            "size":{
              "width":362,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"591c57429a9d460f82a467b7fbefd07d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FF33},
                "location":{
                  "x":128,
                  "y":240},
                "size":{
                  "width":362,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open New Doc Page in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"new_doc_page.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/uploading/u38.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "787cdbb863f04f9e98ae410b455befdb":{
      "scriptId":"u0"},
    "1e824d852ff1408389667790ac517fbb":{
      "scriptId":"u1"},
    "50a02e0cd53d42b1ad0e68ff683f0ab1":{
      "scriptId":"u2"},
    "67dfd745a1d8482b83e4c14f3e8d29f2":{
      "scriptId":"u3"},
    "5dc87becc571486fafb491d550a41f0a":{
      "scriptId":"u4"},
    "aa4bfcb5ff5649e7a4ae1ded3c96540d":{
      "scriptId":"u5"},
    "264007395c1544ae8556955e05d5186d":{
      "scriptId":"u6"},
    "e6f99e81f5714254a4bf48480207fd78":{
      "scriptId":"u7"},
    "95e21bbceee947b4b99cafeb4d68f9c8":{
      "scriptId":"u8"},
    "2cf422a0ab644ebcbf9fb10e2b1ab85b":{
      "scriptId":"u9"},
    "18e4689e63d34234afbe7a453cfbaa25":{
      "scriptId":"u10"},
    "2dd3bd8a7f52464380a23ab49bf44527":{
      "scriptId":"u11"},
    "79b2c45c3c2d4eeea819f50da60bf7f0":{
      "scriptId":"u12"},
    "5c63d56901b342d5bfb789fd45202057":{
      "scriptId":"u13"},
    "39b3f4c062934f1f8f930bbf56117062":{
      "scriptId":"u14"},
    "d334c565081648b399986ce58bf3d7ac":{
      "scriptId":"u15"},
    "cda4a4c3882e4b56b8b5ea8b08810fe3":{
      "scriptId":"u16"},
    "cc54f68880f647eda6580b8c58ef02ab":{
      "scriptId":"u17"},
    "22d570c91c48411caaaea742770189e1":{
      "scriptId":"u18"},
    "338e6cbfba7e4f29b407e01932edfcfb":{
      "scriptId":"u19"},
    "79d31a6134db419f855c90a47ecb19f4":{
      "scriptId":"u20"},
    "651a5efd145941cf8c3f4f5e2b0a7d9b":{
      "scriptId":"u21"},
    "38cdbbfea5af4df6bad98dd089a2cf73":{
      "scriptId":"u22"},
    "be21dd2ae41545678ff97178715d5c1e":{
      "scriptId":"u23"},
    "bf2136bf168842c3a5cb7fdc39b63b2f":{
      "scriptId":"u24"},
    "1b75f71ab7254cada2c0fc121d878215":{
      "scriptId":"u25"},
    "43b1fa7c78bf422e9484777b941ae5b9":{
      "scriptId":"u26"},
    "229df1222d2248fabdec68e7cda98db6":{
      "scriptId":"u27"},
    "976f2e1f7a5b4a7082317f991d54a29a":{
      "scriptId":"u28"},
    "8c6b897ac9474fffbb2e6425674b9319":{
      "scriptId":"u29"},
    "ddef09a070664640a639318f03109da6":{
      "scriptId":"u30"},
    "666c91db99664f8892016233f6af8d8d":{
      "scriptId":"u31"},
    "146c6dcc64eb4373b24a249d806c4799":{
      "scriptId":"u32"},
    "488c23682c134dc683db9d89ce31f7a7":{
      "scriptId":"u33"},
    "8a896df8302342a29ea9991e3ec2c347":{
      "scriptId":"u34"},
    "31674f20a20d4000b9328dcbcabc0291":{
      "scriptId":"u35"},
    "4ea10db28378452bb9cbb674ed41fafc":{
      "scriptId":"u36"},
    "fde0caf7ca9e41b6adf6cab6a1cc91c9":{
      "scriptId":"u37"},
    "f0e3c9f0a06342a6a9024da6f29c1e7b":{
      "scriptId":"u38"},
    "591c57429a9d460f82a467b7fbefd07d":{
      "scriptId":"u39"}}});