$axure.loadCurrentPage({
  "url":"news_page_template.html",
  "generationDate":new Date(1396931400574.28),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"71a322d3ba0345c9ae8cee7dd2e78cf5",
    "type":"Axure:Page",
    "name":"News Page template",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1824246f58274314a130066ebc53cd43",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":25,
              "y":198},
            "size":{
              "width":533,
              "height":24},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e12212de4c524b2890268d2e7ad469a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":25,
                  "y":198},
                "size":{
                  "width":533,
                  "height":24},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"44dcc9b404924903915bfa2396703ad7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":319,
              "y":262},
            "size":{
              "width":369,
              "height":272},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9658ff80d6784c48b9f229f459bd235e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":319,
                  "y":262},
                "size":{
                  "width":369,
                  "height":272},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"43d365c5e5064a79ad0f22f1ed08a9a5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":262},
            "size":{
              "width":269,
              "height":269},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"844f23ec77014a59b3be91cf880f7748",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":262},
                "size":{
                  "width":269,
                  "height":269},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"c462a0d216da4497a28b82d63b36912d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":25,
              "y":552},
            "size":{
              "width":629,
              "height":160},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8f11bfebc56439ca5730644240d3e90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":25,
                  "y":552},
                "size":{
                  "width":629,
                  "height":160},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7865c2d6807c45ca8d5639854b933975",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":25,
              "y":225},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bcc1c5b9f3c04de5a0340ed3b533b4de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":25,
                  "y":225},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d0025b9dac64b9e84cac85a7c129b27",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":13},
            "size":{
              "width":231,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cffb0c848a51434dbe522f05c3c755a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":13},
                "size":{
                  "width":231,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"b876e49738624a4d8e147306c542141a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":123},
            "size":{
              "width":195,
              "height":52},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bddc9d65a56a407281dd903db2910396",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":123},
                "size":{
                  "width":195,
                  "height":52},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open News in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"news.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"f2c9c4a53a9847738087becbb9e0a52f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":208,
              "y":123},
            "size":{
              "width":195,
              "height":52},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"605f228f5ae0443c9276869c60e3c3f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":208,
                  "y":123},
                "size":{
                  "width":195,
                  "height":52},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 2",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Services in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"services.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"28fbadcc74be404aa0cc1e6e93a3ec4d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":403,
              "y":123},
            "size":{
              "width":195,
              "height":52},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e488badcba8f4a54afd212e1f89907fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":403,
                  "y":123},
                "size":{
                  "width":195,
                  "height":52},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Student Activities in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"student_activities.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"54b1034bd16b48c29aaa2ff8be4a9e7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":597,
              "y":123},
            "size":{
              "width":195,
              "height":52},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"775e72114b764c5e9c2f48e47f366767",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":597,
                  "y":123},
                "size":{
                  "width":195,
                  "height":52},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Portfolio in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"portfolio.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"7194eb101b414356b028e7743bfa663b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":583,
              "y":74},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"16c609a531c54c819f2799b92679df0e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":175,
              "y":109},
            "size":{
              "width":23,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b177cfdfb8a4658859af16e24eeaee5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":175,
                  "y":109},
                "size":{
                  "width":23,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC0000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u29.png"}},
{
          "id":"446155e9f5f34245b6ec0d9b12d7ebf8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":597,
              "y":13},
            "size":{
              "width":208,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7aaf49af39e648a2ada8ade4d19326d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":597,
                  "y":13},
                "size":{
                  "width":208,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "1824246f58274314a130066ebc53cd43":{
      "scriptId":"u0"},
    "e12212de4c524b2890268d2e7ad469a6":{
      "scriptId":"u1"},
    "44dcc9b404924903915bfa2396703ad7":{
      "scriptId":"u2"},
    "9658ff80d6784c48b9f229f459bd235e":{
      "scriptId":"u3"},
    "43d365c5e5064a79ad0f22f1ed08a9a5":{
      "scriptId":"u4"},
    "844f23ec77014a59b3be91cf880f7748":{
      "scriptId":"u5"},
    "c462a0d216da4497a28b82d63b36912d":{
      "scriptId":"u6"},
    "f8f11bfebc56439ca5730644240d3e90":{
      "scriptId":"u7"},
    "7865c2d6807c45ca8d5639854b933975":{
      "scriptId":"u8"},
    "bcc1c5b9f3c04de5a0340ed3b533b4de":{
      "scriptId":"u9"},
    "2d0025b9dac64b9e84cac85a7c129b27":{
      "scriptId":"u10"},
    "cffb0c848a51434dbe522f05c3c755a7":{
      "scriptId":"u11"},
    "b876e49738624a4d8e147306c542141a":{
      "scriptId":"u12"},
    "bddc9d65a56a407281dd903db2910396":{
      "scriptId":"u13"},
    "f2c9c4a53a9847738087becbb9e0a52f":{
      "scriptId":"u14"},
    "605f228f5ae0443c9276869c60e3c3f9":{
      "scriptId":"u15"},
    "28fbadcc74be404aa0cc1e6e93a3ec4d":{
      "scriptId":"u16"},
    "e488badcba8f4a54afd212e1f89907fd":{
      "scriptId":"u17"},
    "54b1034bd16b48c29aaa2ff8be4a9e7f":{
      "scriptId":"u18"},
    "775e72114b764c5e9c2f48e47f366767":{
      "scriptId":"u19"},
    "7194eb101b414356b028e7743bfa663b":{
      "scriptId":"u20"},
    "16c609a531c54c819f2799b92679df0e":{
      "scriptId":"u21"},
    "3b177cfdfb8a4658859af16e24eeaee5":{
      "scriptId":"u22"},
    "446155e9f5f34245b6ec0d9b12d7ebf8":{
      "scriptId":"u23"},
    "7aaf49af39e648a2ada8ade4d19326d4":{
      "scriptId":"u24"}}});