$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1397006830299.92),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c978672a96f1458f84e8b8487ad4641c",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ee6304cfdfd349b2bf38bf8ddef7ed8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":61,
              "y":29},
            "size":{
              "width":361,
              "height":555},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c531cc49da5a48a1b97679b5b2d7871e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":61,
                  "y":29},
                "size":{
                  "width":361,
                  "height":555},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"479a1bb4b060448fae019d4cdd532058",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":77,
              "y":68},
            "size":{
              "width":325,
              "height":429},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea5c11be34194a5c91b2b7fffb5ca26a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":77,
                  "y":68},
                "size":{
                  "width":325,
                  "height":429},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"498fb634c6e2407299b33e72a2a6c860",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":214,
              "y":516},
            "size":{
              "width":52,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0574a1f63d734ddeae63f5e799dd10d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":214,
                  "y":516},
                "size":{
                  "width":52,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"2a40ef17c7ec46f59457056b3434fccf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":86,
              "y":90},
            "size":{
              "width":103,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd727953b44c4339a9e7a7f2d1c7841a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":86,
                  "y":90},
                "size":{
                  "width":103,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u6.png"}},
{
          "id":"da215efe41a74dd19fee5486ebd18f8d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontStyle":"italic",
            "location":{
              "x":116.5,
              "y":178},
            "size":{
              "width":246,
              "height":27}},
          "adaptiveStyles":{
}},
{
          "id":"1ba1404996544547ae1101c7f28f71de",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":148,
              "y":222},
            "size":{
              "width":90,
              "height":90},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6be880948ba640ce9892ebd414b72fcb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":148,
                  "y":222},
                "size":{
                  "width":90,
                  "height":90},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u9.png"}},
{
          "id":"29b05fdd736b48428525d68708b54801",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":246,
              "y":222},
            "size":{
              "width":90,
              "height":90},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23c7d0d905ab466d95ee1309bb405b46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":246,
                  "y":222},
                "size":{
                  "width":90,
                  "height":90},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u9.png"}},
{
          "id":"4e544e6ece6e49cd831a979e4b351402",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":148,
              "y":321},
            "size":{
              "width":90,
              "height":90},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f52f0517f6ab47f28ef526c02033d8db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":148,
                  "y":321},
                "size":{
                  "width":90,
                  "height":90},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Both labs in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"both_labs.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u9.png"}},
{
          "id":"ecf7e734e0af44f6826e01afc5970698",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":246,
              "y":321},
            "size":{
              "width":90,
              "height":90},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a138e2f36dcf41b0a84c72eb40ddd233",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":246,
                  "y":321},
                "size":{
                  "width":90,
                  "height":90},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u9.png"}},
{
          "id":"6a5f8899fb21440db7724cb4ce11e748",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":327,
              "y":77},
            "size":{
              "width":69,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"fff4f172bda34d8996db6004b129732b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":162,
              "y":436},
            "size":{
              "width":146,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c9a30c4c1fb542fea1aa0bc3b000d08a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":86,
              "y":436},
            "size":{
              "width":66,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4d0c4b28ec4444c4b85abb769c427d5c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":318,
              "y":436},
            "size":{
              "width":78,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"128912bdbb9041ee8c14f4290a2879c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":285,
              "y":429},
            "size":{
              "width":23,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9228df2d74a54ac285ac696c068b126a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":285,
                  "y":429},
                "size":{
                  "width":23,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u21.png"}},
{
          "id":"60b0f4b5c84447f69b05ab2dcc8fc23b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":291,
              "y":433},
            "size":{
              "width":17,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"779a6129bfcd470eac24c3f24f5206f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":291,
                  "y":433},
                "size":{
                  "width":17,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "ee6304cfdfd349b2bf38bf8ddef7ed8e":{
      "scriptId":"u0"},
    "c531cc49da5a48a1b97679b5b2d7871e":{
      "scriptId":"u1"},
    "479a1bb4b060448fae019d4cdd532058":{
      "scriptId":"u2"},
    "ea5c11be34194a5c91b2b7fffb5ca26a":{
      "scriptId":"u3"},
    "498fb634c6e2407299b33e72a2a6c860":{
      "scriptId":"u4"},
    "0574a1f63d734ddeae63f5e799dd10d2":{
      "scriptId":"u5"},
    "2a40ef17c7ec46f59457056b3434fccf":{
      "scriptId":"u6"},
    "fd727953b44c4339a9e7a7f2d1c7841a":{
      "scriptId":"u7"},
    "da215efe41a74dd19fee5486ebd18f8d":{
      "scriptId":"u8"},
    "1ba1404996544547ae1101c7f28f71de":{
      "scriptId":"u9"},
    "6be880948ba640ce9892ebd414b72fcb":{
      "scriptId":"u10"},
    "29b05fdd736b48428525d68708b54801":{
      "scriptId":"u11"},
    "23c7d0d905ab466d95ee1309bb405b46":{
      "scriptId":"u12"},
    "4e544e6ece6e49cd831a979e4b351402":{
      "scriptId":"u13"},
    "f52f0517f6ab47f28ef526c02033d8db":{
      "scriptId":"u14"},
    "ecf7e734e0af44f6826e01afc5970698":{
      "scriptId":"u15"},
    "a138e2f36dcf41b0a84c72eb40ddd233":{
      "scriptId":"u16"},
    "6a5f8899fb21440db7724cb4ce11e748":{
      "scriptId":"u17"},
    "fff4f172bda34d8996db6004b129732b":{
      "scriptId":"u18"},
    "c9a30c4c1fb542fea1aa0bc3b000d08a":{
      "scriptId":"u19"},
    "4d0c4b28ec4444c4b85abb769c427d5c":{
      "scriptId":"u20"},
    "128912bdbb9041ee8c14f4290a2879c9":{
      "scriptId":"u21"},
    "9228df2d74a54ac285ac696c068b126a":{
      "scriptId":"u22"},
    "60b0f4b5c84447f69b05ab2dcc8fc23b":{
      "scriptId":"u23"},
    "779a6129bfcd470eac24c3f24f5206f4":{
      "scriptId":"u24"}}});