$axure.loadCurrentPage({
  "url":"portfolio.html",
  "generationDate":new Date(1396931401671.34),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1ecf2b74a355459e92ce4e3f68165164",
    "type":"Axure:Page",
    "name":"Portfolio",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"354c637e3c914f3c98f0af03365e55ff",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":573,
              "y":198},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Upload a File in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"upload_a_file.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"b1de148329e54e0e967881288c11e14f",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":322,
              "y":194},
            "size":{
              "width":180,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"daa06a519ec0467da21f22b4cc571fca",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":75,
              "y":267},
            "size":{
              "width":271,
              "height":175}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"822d582ba19a4f86a4e8bf3f8d9e419e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":75,
                  "y":267},
                "size":{
                  "width":271,
                  "height":175}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Video/Game in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"video_game.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/portfolio/u2.png"}},
{
          "id":"90c9da570c964429a0ce3b0c89e8d5cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":365,
              "y":267},
            "size":{
              "width":338,
              "height":175}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68681781c0e3455ea98f472834a77b99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":365,
                  "y":267},
                "size":{
                  "width":338,
                  "height":175}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Document Page in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"document_page.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/portfolio/u4.png"}},
{
          "id":"151bad0277cd47fd984ab23486995fa2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":75,
              "y":452},
            "size":{
              "width":628,
              "height":261}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9179920f276452e8ee6c80f00a6bb6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":75,
                  "y":452},
                "size":{
                  "width":628,
                  "height":261}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Video/Game in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"video_game.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/portfolio/u6.png"}},
{
          "id":"3af92ff629264d2f8dc55275fefa537e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":75,
              "y":723},
            "size":{
              "width":338,
              "height":175}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39f2ff800cfa4130a984140a7da15c3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":75,
                  "y":723},
                "size":{
                  "width":338,
                  "height":175}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Document Page in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"document_page.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/portfolio/u4.png"}},
{
          "id":"e91cd27250bc4dfa88e77a45f4559b1d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":429,
              "y":723},
            "size":{
              "width":274,
              "height":175}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9de08e39095048a5861debccbe18c5d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":429,
                  "y":723},
                "size":{
                  "width":274,
                  "height":175}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Document Page in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"document_page.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/portfolio/u10.png"}},
{
          "id":"d70afe603b8c4d5c9cb93c5f734572eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":75,
              "y":908},
            "size":{
              "width":628,
              "height":57}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de7791e9de104de4a5ae240a4e249c16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":75,
                  "y":908},
                "size":{
                  "width":628,
                  "height":57}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/portfolio/u12.png"}},
{
          "id":"305d14cf1224468280473a7162ac7e42",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":597,
              "y":13},
            "size":{
              "width":208,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0d569cdb4ee4f10a308adb67a2c4271",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":597,
                  "y":13},
                "size":{
                  "width":208,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba0e968317684ee59faf05972ee323db",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":94,
              "y":198},
            "size":{
              "width":176,
              "height":25},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc634f94410a4c1b9b4a54a2d8a737bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":94,
                  "y":198},
                "size":{
                  "width":176,
                  "height":25},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/portfolio/u16.png"}},
{
          "id":"ec5de0b8677d4754a34940943ce88eec",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":13},
            "size":{
              "width":231,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3d66ca230e741abbf82dab958f3a914",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":13},
                "size":{
                  "width":231,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"b372b4e9ba4a4dee8f51bd6e0b50828a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":123},
            "size":{
              "width":195,
              "height":52},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc70881a1c934775ba86401a8ddb9e6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":123},
                "size":{
                  "width":195,
                  "height":52},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open News in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"news.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"df8976e68d554d44a2c78a0904ebd92f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":208,
              "y":123},
            "size":{
              "width":195,
              "height":52},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e1818bfd3a646778d919fb92eda0266",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":208,
                  "y":123},
                "size":{
                  "width":195,
                  "height":52},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 2",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Services in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"services.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"12a68f97a84a4dffaecad279b2fc9d25",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":403,
              "y":123},
            "size":{
              "width":195,
              "height":52},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a069ddab82345c0b7f429ec16c1f464",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":403,
                  "y":123},
                "size":{
                  "width":195,
                  "height":52},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Student Activities in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"student_activities.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"03f3979e38924c72ab1cbf26ea175c2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":597,
              "y":123},
            "size":{
              "width":195,
              "height":52},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0843fa04fa4412996cea67c1c8e578b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":597,
                  "y":123},
                "size":{
                  "width":195,
                  "height":52},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Portfolio in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"portfolio.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"097705b7a9e24df6b681b04ef4dea2bc",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":583,
              "y":74},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"66852bd71bd940ac83bae0f7c7cdeb85",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":175,
              "y":109},
            "size":{
              "width":23,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"723ed6713e3e4c7695c431f63e869fbd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":175,
                  "y":109},
                "size":{
                  "width":23,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC0000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u29.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "354c637e3c914f3c98f0af03365e55ff":{
      "scriptId":"u0"},
    "b1de148329e54e0e967881288c11e14f":{
      "scriptId":"u1"},
    "daa06a519ec0467da21f22b4cc571fca":{
      "scriptId":"u2"},
    "822d582ba19a4f86a4e8bf3f8d9e419e":{
      "scriptId":"u3"},
    "90c9da570c964429a0ce3b0c89e8d5cf":{
      "scriptId":"u4"},
    "68681781c0e3455ea98f472834a77b99":{
      "scriptId":"u5"},
    "151bad0277cd47fd984ab23486995fa2":{
      "scriptId":"u6"},
    "f9179920f276452e8ee6c80f00a6bb6b":{
      "scriptId":"u7"},
    "3af92ff629264d2f8dc55275fefa537e":{
      "scriptId":"u8"},
    "39f2ff800cfa4130a984140a7da15c3d":{
      "scriptId":"u9"},
    "e91cd27250bc4dfa88e77a45f4559b1d":{
      "scriptId":"u10"},
    "9de08e39095048a5861debccbe18c5d0":{
      "scriptId":"u11"},
    "d70afe603b8c4d5c9cb93c5f734572eb":{
      "scriptId":"u12"},
    "de7791e9de104de4a5ae240a4e249c16":{
      "scriptId":"u13"},
    "305d14cf1224468280473a7162ac7e42":{
      "scriptId":"u14"},
    "c0d569cdb4ee4f10a308adb67a2c4271":{
      "scriptId":"u15"},
    "ba0e968317684ee59faf05972ee323db":{
      "scriptId":"u16"},
    "fc634f94410a4c1b9b4a54a2d8a737bc":{
      "scriptId":"u17"},
    "ec5de0b8677d4754a34940943ce88eec":{
      "scriptId":"u18"},
    "d3d66ca230e741abbf82dab958f3a914":{
      "scriptId":"u19"},
    "b372b4e9ba4a4dee8f51bd6e0b50828a":{
      "scriptId":"u20"},
    "bc70881a1c934775ba86401a8ddb9e6e":{
      "scriptId":"u21"},
    "df8976e68d554d44a2c78a0904ebd92f":{
      "scriptId":"u22"},
    "4e1818bfd3a646778d919fb92eda0266":{
      "scriptId":"u23"},
    "12a68f97a84a4dffaecad279b2fc9d25":{
      "scriptId":"u24"},
    "0a069ddab82345c0b7f429ec16c1f464":{
      "scriptId":"u25"},
    "03f3979e38924c72ab1cbf26ea175c2b":{
      "scriptId":"u26"},
    "c0843fa04fa4412996cea67c1c8e578b":{
      "scriptId":"u27"},
    "097705b7a9e24df6b681b04ef4dea2bc":{
      "scriptId":"u28"},
    "66852bd71bd940ac83bae0f7c7cdeb85":{
      "scriptId":"u29"},
    "723ed6713e3e4c7695c431f63e869fbd":{
      "scriptId":"u30"}}});