$axure.loadCurrentPage({
  "url":"both_labs.html",
  "generationDate":new Date(1397006830672.94),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"72ca707479b949fe8e5b1255d2887ee9",
    "type":"Axure:Page",
    "name":"Both labs",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"91dc623be1144747b4f1c63692ab4601",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":61,
              "y":29},
            "size":{
              "width":361,
              "height":555},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b5e1fc48ce54d49bf660f6b57dcf53d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":61,
                  "y":29},
                "size":{
                  "width":361,
                  "height":555},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"bdc756956a6c4f9599ab6fec6596c86a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":77,
              "y":68},
            "size":{
              "width":325,
              "height":429},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05ccf3f4f5c24c8896995e3f1185a5b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":77,
                  "y":68},
                "size":{
                  "width":325,
                  "height":429},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lp_labs/u2.png"}},
{
          "id":"df31fa9f6f624a4c9555c89772d5dd5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":214,
              "y":516},
            "size":{
              "width":52,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9e012bd36074846b05a6d41213ca879",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":214,
                  "y":516},
                "size":{
                  "width":52,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"aa2037e586a341bf8ae459d23a4eb995",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":77,
              "y":68},
            "size":{
              "width":325,
              "height":87}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aeb76daed2184439b4ed1df02c5b5edb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":77,
                  "y":68},
                "size":{
                  "width":325,
                  "height":87}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lp_labs/u6.png"}},
{
          "id":"213bf2e6727944eb8f1ca9c593695560",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":327,
              "y":77},
            "size":{
              "width":69,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"4312040cf977472ab963c9eea7b98948",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":81,
              "y":77},
            "size":{
              "width":55,
              "height":24},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"145f6c58e0af4caba630a56246124681",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":81,
                  "y":77},
                "size":{
                  "width":55,
                  "height":24},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/lp_labs/u66.png"}},
{
          "id":"0908832e01ec471fb6fb55b8d7b78c13",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":146,
              "y":77},
            "size":{
              "width":69,
              "height":22}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"615a19c554994553a7c51ef9720bfefa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":164,
              "y":122},
            "size":{
              "width":150,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc0bb69c2182492ea44b112c94311d61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":164,
                  "y":122},
                "size":{
                  "width":150,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d54700d1acfe4642bf48d1630599bd24",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFF0099CC},
            "location":{
              "x":77,
              "y":165},
            "size":{
              "width":325,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"692068a55c634604a5f7d3924327ce04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099CC},
                "location":{
                  "x":77,
                  "y":165},
                "size":{
                  "width":325,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open LP labs in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"lp_labs.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/lp_labs/u11.png"}},
{
          "id":"ca7b672d277244ba8156325e41c3539a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":77,
              "y":198},
            "size":{
              "width":325,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b948412494d41d4b3e1f85669b1c6b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":77,
                  "y":198},
                "size":{
                  "width":325,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Loop labs in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"loop_labs.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/lp_labs/u64.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "91dc623be1144747b4f1c63692ab4601":{
      "scriptId":"u0"},
    "6b5e1fc48ce54d49bf660f6b57dcf53d":{
      "scriptId":"u1"},
    "bdc756956a6c4f9599ab6fec6596c86a":{
      "scriptId":"u2"},
    "05ccf3f4f5c24c8896995e3f1185a5b1":{
      "scriptId":"u3"},
    "df31fa9f6f624a4c9555c89772d5dd5e":{
      "scriptId":"u4"},
    "b9e012bd36074846b05a6d41213ca879":{
      "scriptId":"u5"},
    "aa2037e586a341bf8ae459d23a4eb995":{
      "scriptId":"u6"},
    "aeb76daed2184439b4ed1df02c5b5edb":{
      "scriptId":"u7"},
    "213bf2e6727944eb8f1ca9c593695560":{
      "scriptId":"u8"},
    "4312040cf977472ab963c9eea7b98948":{
      "scriptId":"u9"},
    "145f6c58e0af4caba630a56246124681":{
      "scriptId":"u10"},
    "0908832e01ec471fb6fb55b8d7b78c13":{
      "scriptId":"u11"},
    "615a19c554994553a7c51ef9720bfefa":{
      "scriptId":"u12"},
    "cc0bb69c2182492ea44b112c94311d61":{
      "scriptId":"u13"},
    "d54700d1acfe4642bf48d1630599bd24":{
      "scriptId":"u14"},
    "692068a55c634604a5f7d3924327ce04":{
      "scriptId":"u15"},
    "ca7b672d277244ba8156325e41c3539a":{
      "scriptId":"u16"},
    "7b948412494d41d4b3e1f85669b1c6b3":{
      "scriptId":"u17"}}});