$axure.loadCurrentPage({
  "url":"clubs_activities.html",
  "generationDate":new Date(1396931401252.32),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ebe30981d0b74f0a81d59b9485d178a5",
    "type":"Axure:Page",
    "name":"Clubs/Activities",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e5b56aeef31d433389552b880847f1eb",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":326,
              "y":197.5},
            "size":{
              "width":180,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"d467a50af10040178de167317e895aaa",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontStyle":"italic",
            "location":{
              "x":516,
              "y":195},
            "size":{
              "width":229,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6b4941dd73bc4760b819379416d146f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":239},
            "size":{
              "width":350,
              "height":189}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7efdf8714d994b8c82427cd6d1b12a48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":239},
                "size":{
                  "width":350,
                  "height":189}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/student_activities/u2.png"}},
{
          "id":"570b3fe7e7cb4b079f30c998d14381ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":452},
            "size":{
              "width":350,
              "height":189}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a09e42f556f947e188efd42fe1426bbf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":452},
                "size":{
                  "width":350,
                  "height":189}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/student_activities/u2.png"}},
{
          "id":"eb935d5f1e984a3bbff462aa521bdc85",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":667},
            "size":{
              "width":350,
              "height":189}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00a9fa4a92ed4ad98ae87a4bd0cd7a7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":667},
                "size":{
                  "width":350,
                  "height":189}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/student_activities/u2.png"}},
{
          "id":"ec14ddabd2ac4768aafbb0a076f58c41",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":1102},
            "size":{
              "width":622,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40741fee64304586a993d9415dc44191",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":1102},
                "size":{
                  "width":622,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/student_activities/u8.png"}},
{
          "id":"688ed897a9b0475c811da038d59900d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":424,
              "y":239},
            "size":{
              "width":321,
              "height":264}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df25d3712b0f46b99d34a2cca2e8320d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":424,
                  "y":239},
                "size":{
                  "width":321,
                  "height":264}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/student_activities/u10.png"}},
{
          "id":"cff50e92040341168a763c4fb1b1504a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":442,
              "y":247},
            "size":{
              "width":226,
              "height":22},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f63d4e4c7504b33bad7af6307512029",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":442,
                  "y":247},
                "size":{
                  "width":226,
                  "height":22},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"53923532a0ff4ed680d07fbacf8a3cf4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":442,
              "y":279},
            "size":{
              "width":87,
              "height":66},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17953208c4be4621b8ad0f3ecdc8f870",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":442,
                  "y":279},
                "size":{
                  "width":87,
                  "height":66},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/student_activities/u14.png"}},
{
          "id":"3092bec241924311804fe13b7cd15fc5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":537,
              "y":279},
            "size":{
              "width":178,
              "height":32},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"061e361c4afb434fb05004804a8a05e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":537,
                  "y":279},
                "size":{
                  "width":178,
                  "height":32},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9ecd6f4645434f9ba3df067162250cce",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":890},
            "size":{
              "width":350,
              "height":189}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2318af5e9a544a2a8d077df2022076f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":890},
                "size":{
                  "width":350,
                  "height":189}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/student_activities/u2.png"}},
{
          "id":"ac9a8b4abc7549f6b786c33d8cac5e74",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":424,
              "y":516},
            "size":{
              "width":321,
              "height":125}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bde07b16cb774ad8a6b90c68e2f13cbe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":424,
                  "y":516},
                "size":{
                  "width":321,
                  "height":125}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/student_activities/u20.png"}},
{
          "id":"aaaa5576b8c74463a9a0c04a302966c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":424,
              "y":651},
            "size":{
              "width":321,
              "height":125}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e9cc9e8fb67428095ae3d133e4423c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":424,
                  "y":651},
                "size":{
                  "width":321,
                  "height":125}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/student_activities/u20.png"}},
{
          "id":"f67fcbc2b9ce48889222b4f3dc4e0f0c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":239},
            "size":{
              "width":150,
              "height":110},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7c669e5992f4e8699d5a2e6239abd2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":239},
                "size":{
                  "width":150,
                  "height":110},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"d79e16a6c9c14a7b8f8db6bd57d460bb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":349},
            "size":{
              "width":150,
              "height":78},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"310a9fc34e9944f6ba8a7ebe9ab3cbaa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":349},
                "size":{
                  "width":150,
                  "height":78},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"8730addbe53b4ad9ac2c74b90b9e3dc4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":267,
              "y":239},
            "size":{
              "width":109,
              "height":57},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d24697520e345b8b0f16b4b1feea5e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":267,
                  "y":239},
                "size":{
                  "width":109,
                  "height":57},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"45192bd3224247e9972b5d261f4a16a2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":267,
              "y":296},
            "size":{
              "width":109,
              "height":85},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6fd7dd71ac94066bcefcaf7101e0b5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":267,
                  "y":296},
                "size":{
                  "width":109,
                  "height":85},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"9eb691cf8cc548329c6faa4ae255bad7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":176,
              "y":381},
            "size":{
              "width":200,
              "height":47},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d21c88ed918444fa3cfdef56efcc752",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":176,
                  "y":381},
                "size":{
                  "width":200,
                  "height":47},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"50674fb972824009adcb0950b1f723b4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":176,
              "y":239},
            "size":{
              "width":91,
              "height":142},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f94bf07630c4936b37a55b085fcb830",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":176,
                  "y":239},
                "size":{
                  "width":91,
                  "height":142},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"23317fa47d874dc3a2d7de1c71a55f3d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":312},
            "size":{
              "width":231,
              "height":59}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62b21d6df408454bbf28688620a9d53b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":312},
                "size":{
                  "width":231,
                  "height":59}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Student Profile in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"student_profile.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/student_activities/u36.png"}},
{
          "id":"5b8397714df0440882ef989778e75939",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":452},
            "size":{
              "width":150,
              "height":110},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59cede3ecf594c92a32279771fbee055",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":452},
                "size":{
                  "width":150,
                  "height":110},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"08191615076f42d7a5629993ba58b60f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":562},
            "size":{
              "width":150,
              "height":78},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eac34874ab0a4728b7971c9ca81dca0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":562},
                "size":{
                  "width":150,
                  "height":78},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"aeaa9565f0134dff8452ee7084415868",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":267,
              "y":452},
            "size":{
              "width":109,
              "height":57},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f96a4eee981947168e329ae3b3fa6430",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":267,
                  "y":452},
                "size":{
                  "width":109,
                  "height":57},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"3b536617f6a2410cb61b0e8489b72f22",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":267,
              "y":509},
            "size":{
              "width":109,
              "height":85},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41f211cbf3174aa8ad2adf8a4f98635e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":267,
                  "y":509},
                "size":{
                  "width":109,
                  "height":85},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"a15799ee46db40c094fb6815e18fc909",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":176,
              "y":594},
            "size":{
              "width":200,
              "height":47},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b33ff7de6162418fa94443ff2abccb96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":176,
                  "y":594},
                "size":{
                  "width":200,
                  "height":47},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"6640c9faed284205a8c580df1bfbd715",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":176,
              "y":452},
            "size":{
              "width":91,
              "height":142},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0666721f0784b47b47e005dfd5436b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":176,
                  "y":452},
                "size":{
                  "width":91,
                  "height":142},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"733fec7b1de741d295442dc6ffb5ab1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":525},
            "size":{
              "width":231,
              "height":59}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b7c12974821416e8a84baadd537003b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":525},
                "size":{
                  "width":231,
                  "height":59}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Student Profile in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"student_profile.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/student_activities/u36.png"}},
{
          "id":"f29c609314374d8ba60845fef17b8814",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":667},
            "size":{
              "width":150,
              "height":110},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ee16f75544745c29c8421e3076ae828",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":667},
                "size":{
                  "width":150,
                  "height":110},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"ae6dd4e9593a4506aca5ca616cbacc36",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":777},
            "size":{
              "width":150,
              "height":78},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4378024506134a259ef2f2e798501696",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":777},
                "size":{
                  "width":150,
                  "height":78},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"949bc383f3004fef942d03f0b1e1d6d8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":267,
              "y":667},
            "size":{
              "width":109,
              "height":57},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c335b62232a74a0ca5b2b877b277566e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":267,
                  "y":667},
                "size":{
                  "width":109,
                  "height":57},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"32f09105a1a14ceb8cfdaf1c2daeff50",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":267,
              "y":724},
            "size":{
              "width":109,
              "height":85},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3de9880a15049dca9f7b86fed6330dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":267,
                  "y":724},
                "size":{
                  "width":109,
                  "height":85},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"b001a7764f0b4c6f9977a59000102c12",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":176,
              "y":809},
            "size":{
              "width":200,
              "height":47},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0fb8a09997c42698e3e2008ebd69c9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":176,
                  "y":809},
                "size":{
                  "width":200,
                  "height":47},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"0734748af3164d86b3377f9a07d0ee8a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":176,
              "y":667},
            "size":{
              "width":91,
              "height":142},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58f27530a08b4222a71fa6e381ee5648",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":176,
                  "y":667},
                "size":{
                  "width":91,
                  "height":142},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"681de04ac445483288639891ccaa687f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":740},
            "size":{
              "width":231,
              "height":59}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"649909c9f54249f78bf317dd22be1d8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":740},
                "size":{
                  "width":231,
                  "height":59}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Student Profile in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"student_profile.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/student_activities/u36.png"}},
{
          "id":"4e37e0c2e7e941b59695a8637a8e01df",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":890},
            "size":{
              "width":150,
              "height":110},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aab876c776fd4887885f2757102fd92e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":890},
                "size":{
                  "width":150,
                  "height":110},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"6d4c2d202f6b4376ae8a5704e1b95891",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":1000},
            "size":{
              "width":150,
              "height":78},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d642caafdb40484a88b3dfd9ec5c368b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":1000},
                "size":{
                  "width":150,
                  "height":78},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"3dc02b1be85d4e54a9175fbb3c2469eb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":267,
              "y":890},
            "size":{
              "width":109,
              "height":57},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d84b5788bfd4292b33355ffd31d67b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":267,
                  "y":890},
                "size":{
                  "width":109,
                  "height":57},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"027035255b664c5199ff4e888fe10b2a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":267,
              "y":947},
            "size":{
              "width":109,
              "height":85},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5efc92b5155d43be9ac49718eacc1014",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":267,
                  "y":947},
                "size":{
                  "width":109,
                  "height":85},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"bee1c8b62d3148ef975e172fcf25584b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":176,
              "y":1032},
            "size":{
              "width":200,
              "height":47},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc08f74db53444dc94d8b9071d5eae07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":176,
                  "y":1032},
                "size":{
                  "width":200,
                  "height":47},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"2502f8ae34b84d5c9c48e23a33397fb3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":176,
              "y":890},
            "size":{
              "width":91,
              "height":142},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6757ef26af134efc95f48bf05844c993",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":176,
                  "y":890},
                "size":{
                  "width":91,
                  "height":142},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"cc6c4679942641e4a4550db7fe7e4abe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":963},
            "size":{
              "width":231,
              "height":59}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29fb4ba10620401298b9f23512a9a768",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":963},
                "size":{
                  "width":231,
                  "height":59}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Student Profile in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"student_profile.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/student_activities/u36.png"}},
{
          "id":"ee1f6d63db7841b9982ad2825755d78b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":13},
            "size":{
              "width":231,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01a3129b8a1e4996814b3c364efc10d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":13},
                "size":{
                  "width":231,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"3a6dc12a12464a30b97729bd758521e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":123},
            "size":{
              "width":195,
              "height":52},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f06c216788b4721945ae4993cd0555f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":123},
                "size":{
                  "width":195,
                  "height":52},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open News in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"news.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"1c6caa9ef49f4464a0dbc495a3b861b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":208,
              "y":123},
            "size":{
              "width":195,
              "height":52},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a4469e1b2c54627bdbf7040dec88f6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":208,
                  "y":123},
                "size":{
                  "width":195,
                  "height":52},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 2",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Services in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"services.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"1645cdd9fa734fabaecf0214a6176a56",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":403,
              "y":123},
            "size":{
              "width":195,
              "height":52},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"494dc4b4d4da40bf81978df6fc7b358b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":403,
                  "y":123},
                "size":{
                  "width":195,
                  "height":52},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Student Activities in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"student_activities.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"afafe28e10884ed0b8e1a15aad7f91e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":597,
              "y":123},
            "size":{
              "width":195,
              "height":52},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df5f9c4a7e064eed8c1d58eaf785520c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":597,
                  "y":123},
                "size":{
                  "width":195,
                  "height":52},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Portfolio in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"portfolio.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"052352be11204cc08e3fc19e9026573b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":583,
              "y":74},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"5536a9bd6b934713a91ef39be31b46f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":175,
              "y":109},
            "size":{
              "width":23,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"047f1760c906445a9cc6e07847ef35f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":175,
                  "y":109},
                "size":{
                  "width":23,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC0000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u29.png"}},
{
          "id":"92ffd9b0f00e49ccb305d7e53c07040d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":597,
              "y":13},
            "size":{
              "width":208,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05b6e92dc79f4f4e8cf2121c1ca2c48e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":597,
                  "y":13},
                "size":{
                  "width":208,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6e0bf3849de642d188cd45e900f8f58a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":196},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Student Activities in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"student_activities.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"cfc3356f4dc649c6b947789a51c29e02",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":136,
              "y":196},
            "size":{
              "width":155,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Clubs/Activities in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"clubs_activities.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "e5b56aeef31d433389552b880847f1eb":{
      "scriptId":"u0"},
    "d467a50af10040178de167317e895aaa":{
      "scriptId":"u1"},
    "6b4941dd73bc4760b819379416d146f6":{
      "scriptId":"u2"},
    "7efdf8714d994b8c82427cd6d1b12a48":{
      "scriptId":"u3"},
    "570b3fe7e7cb4b079f30c998d14381ef":{
      "scriptId":"u4"},
    "a09e42f556f947e188efd42fe1426bbf":{
      "scriptId":"u5"},
    "eb935d5f1e984a3bbff462aa521bdc85":{
      "scriptId":"u6"},
    "00a9fa4a92ed4ad98ae87a4bd0cd7a7a":{
      "scriptId":"u7"},
    "ec14ddabd2ac4768aafbb0a076f58c41":{
      "scriptId":"u8"},
    "40741fee64304586a993d9415dc44191":{
      "scriptId":"u9"},
    "688ed897a9b0475c811da038d59900d0":{
      "scriptId":"u10"},
    "df25d3712b0f46b99d34a2cca2e8320d":{
      "scriptId":"u11"},
    "cff50e92040341168a763c4fb1b1504a":{
      "scriptId":"u12"},
    "0f63d4e4c7504b33bad7af6307512029":{
      "scriptId":"u13"},
    "53923532a0ff4ed680d07fbacf8a3cf4":{
      "scriptId":"u14"},
    "17953208c4be4621b8ad0f3ecdc8f870":{
      "scriptId":"u15"},
    "3092bec241924311804fe13b7cd15fc5":{
      "scriptId":"u16"},
    "061e361c4afb434fb05004804a8a05e1":{
      "scriptId":"u17"},
    "9ecd6f4645434f9ba3df067162250cce":{
      "scriptId":"u18"},
    "2318af5e9a544a2a8d077df2022076f2":{
      "scriptId":"u19"},
    "ac9a8b4abc7549f6b786c33d8cac5e74":{
      "scriptId":"u20"},
    "bde07b16cb774ad8a6b90c68e2f13cbe":{
      "scriptId":"u21"},
    "aaaa5576b8c74463a9a0c04a302966c3":{
      "scriptId":"u22"},
    "0e9cc9e8fb67428095ae3d133e4423c7":{
      "scriptId":"u23"},
    "f67fcbc2b9ce48889222b4f3dc4e0f0c":{
      "scriptId":"u24"},
    "d7c669e5992f4e8699d5a2e6239abd2c":{
      "scriptId":"u25"},
    "d79e16a6c9c14a7b8f8db6bd57d460bb":{
      "scriptId":"u26"},
    "310a9fc34e9944f6ba8a7ebe9ab3cbaa":{
      "scriptId":"u27"},
    "8730addbe53b4ad9ac2c74b90b9e3dc4":{
      "scriptId":"u28"},
    "2d24697520e345b8b0f16b4b1feea5e6":{
      "scriptId":"u29"},
    "45192bd3224247e9972b5d261f4a16a2":{
      "scriptId":"u30"},
    "e6fd7dd71ac94066bcefcaf7101e0b5d":{
      "scriptId":"u31"},
    "9eb691cf8cc548329c6faa4ae255bad7":{
      "scriptId":"u32"},
    "1d21c88ed918444fa3cfdef56efcc752":{
      "scriptId":"u33"},
    "50674fb972824009adcb0950b1f723b4":{
      "scriptId":"u34"},
    "8f94bf07630c4936b37a55b085fcb830":{
      "scriptId":"u35"},
    "23317fa47d874dc3a2d7de1c71a55f3d":{
      "scriptId":"u36"},
    "62b21d6df408454bbf28688620a9d53b":{
      "scriptId":"u37"},
    "5b8397714df0440882ef989778e75939":{
      "scriptId":"u38"},
    "59cede3ecf594c92a32279771fbee055":{
      "scriptId":"u39"},
    "08191615076f42d7a5629993ba58b60f":{
      "scriptId":"u40"},
    "eac34874ab0a4728b7971c9ca81dca0d":{
      "scriptId":"u41"},
    "aeaa9565f0134dff8452ee7084415868":{
      "scriptId":"u42"},
    "f96a4eee981947168e329ae3b3fa6430":{
      "scriptId":"u43"},
    "3b536617f6a2410cb61b0e8489b72f22":{
      "scriptId":"u44"},
    "41f211cbf3174aa8ad2adf8a4f98635e":{
      "scriptId":"u45"},
    "a15799ee46db40c094fb6815e18fc909":{
      "scriptId":"u46"},
    "b33ff7de6162418fa94443ff2abccb96":{
      "scriptId":"u47"},
    "6640c9faed284205a8c580df1bfbd715":{
      "scriptId":"u48"},
    "f0666721f0784b47b47e005dfd5436b4":{
      "scriptId":"u49"},
    "733fec7b1de741d295442dc6ffb5ab1c":{
      "scriptId":"u50"},
    "2b7c12974821416e8a84baadd537003b":{
      "scriptId":"u51"},
    "f29c609314374d8ba60845fef17b8814":{
      "scriptId":"u52"},
    "6ee16f75544745c29c8421e3076ae828":{
      "scriptId":"u53"},
    "ae6dd4e9593a4506aca5ca616cbacc36":{
      "scriptId":"u54"},
    "4378024506134a259ef2f2e798501696":{
      "scriptId":"u55"},
    "949bc383f3004fef942d03f0b1e1d6d8":{
      "scriptId":"u56"},
    "c335b62232a74a0ca5b2b877b277566e":{
      "scriptId":"u57"},
    "32f09105a1a14ceb8cfdaf1c2daeff50":{
      "scriptId":"u58"},
    "e3de9880a15049dca9f7b86fed6330dd":{
      "scriptId":"u59"},
    "b001a7764f0b4c6f9977a59000102c12":{
      "scriptId":"u60"},
    "e0fb8a09997c42698e3e2008ebd69c9a":{
      "scriptId":"u61"},
    "0734748af3164d86b3377f9a07d0ee8a":{
      "scriptId":"u62"},
    "58f27530a08b4222a71fa6e381ee5648":{
      "scriptId":"u63"},
    "681de04ac445483288639891ccaa687f":{
      "scriptId":"u64"},
    "649909c9f54249f78bf317dd22be1d8f":{
      "scriptId":"u65"},
    "4e37e0c2e7e941b59695a8637a8e01df":{
      "scriptId":"u66"},
    "aab876c776fd4887885f2757102fd92e":{
      "scriptId":"u67"},
    "6d4c2d202f6b4376ae8a5704e1b95891":{
      "scriptId":"u68"},
    "d642caafdb40484a88b3dfd9ec5c368b":{
      "scriptId":"u69"},
    "3dc02b1be85d4e54a9175fbb3c2469eb":{
      "scriptId":"u70"},
    "4d84b5788bfd4292b33355ffd31d67b7":{
      "scriptId":"u71"},
    "027035255b664c5199ff4e888fe10b2a":{
      "scriptId":"u72"},
    "5efc92b5155d43be9ac49718eacc1014":{
      "scriptId":"u73"},
    "bee1c8b62d3148ef975e172fcf25584b":{
      "scriptId":"u74"},
    "dc08f74db53444dc94d8b9071d5eae07":{
      "scriptId":"u75"},
    "2502f8ae34b84d5c9c48e23a33397fb3":{
      "scriptId":"u76"},
    "6757ef26af134efc95f48bf05844c993":{
      "scriptId":"u77"},
    "cc6c4679942641e4a4550db7fe7e4abe":{
      "scriptId":"u78"},
    "29fb4ba10620401298b9f23512a9a768":{
      "scriptId":"u79"},
    "ee1f6d63db7841b9982ad2825755d78b":{
      "scriptId":"u80"},
    "01a3129b8a1e4996814b3c364efc10d8":{
      "scriptId":"u81"},
    "3a6dc12a12464a30b97729bd758521e2":{
      "scriptId":"u82"},
    "8f06c216788b4721945ae4993cd0555f":{
      "scriptId":"u83"},
    "1c6caa9ef49f4464a0dbc495a3b861b4":{
      "scriptId":"u84"},
    "7a4469e1b2c54627bdbf7040dec88f6d":{
      "scriptId":"u85"},
    "1645cdd9fa734fabaecf0214a6176a56":{
      "scriptId":"u86"},
    "494dc4b4d4da40bf81978df6fc7b358b":{
      "scriptId":"u87"},
    "afafe28e10884ed0b8e1a15aad7f91e9":{
      "scriptId":"u88"},
    "df5f9c4a7e064eed8c1d58eaf785520c":{
      "scriptId":"u89"},
    "052352be11204cc08e3fc19e9026573b":{
      "scriptId":"u90"},
    "5536a9bd6b934713a91ef39be31b46f6":{
      "scriptId":"u91"},
    "047f1760c906445a9cc6e07847ef35f1":{
      "scriptId":"u92"},
    "92ffd9b0f00e49ccb305d7e53c07040d":{
      "scriptId":"u93"},
    "05b6e92dc79f4f4e8cf2121c1ca2c48e":{
      "scriptId":"u94"},
    "6e0bf3849de642d188cd45e900f8f58a":{
      "scriptId":"u95"},
    "cfc3356f4dc649c6b947789a51c29e02":{
      "scriptId":"u96"}}});