$axure.loadCurrentPage({
  "url":"details.html",
  "generationDate":new Date(1397006830628.94),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"824f06e2ed7b4e489ebbeeba6819ce5b",
    "type":"Axure:Page",
    "name":"Details",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8d5404b131b34533ade63c7ae8d0cf0d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":61,
              "y":29},
            "size":{
              "width":361,
              "height":555},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f3684c1de484b7da06d1e464b5d97fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":61,
                  "y":29},
                "size":{
                  "width":361,
                  "height":555},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"548d2dab575e4205b303b3cef1d2882e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":77,
              "y":68},
            "size":{
              "width":325,
              "height":429},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"040e7edb47a84a21bf89ac191524feb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":77,
                  "y":68},
                "size":{
                  "width":325,
                  "height":429},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lp_labs/u2.png"}},
{
          "id":"73d041bc92ef4124be3167f7984aa03b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":214,
              "y":516},
            "size":{
              "width":52,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f5445df073347b0a98f91659f9d0dde",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":214,
                  "y":516},
                "size":{
                  "width":52,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"2f3c6af3ce8f46e1b72bddd28955cc74",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":77,
              "y":68},
            "size":{
              "width":325,
              "height":87}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ebf42b8033241b4bec0ed5bad133ce8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":77,
                  "y":68},
                "size":{
                  "width":325,
                  "height":87}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lp_labs/u6.png"}},
{
          "id":"0110cb41f05442c4a46e059ea9ecd42c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":327,
              "y":77},
            "size":{
              "width":69,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"d4eafe12bb3847f4a9e4a94ee3ae6bcf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":164,
              "y":122},
            "size":{
              "width":150,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb20245f34084c888a0802942f8daa1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":164,
                  "y":122},
                "size":{
                  "width":150,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c247b10a3d004e2bacf143a11874bb77",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":98,
              "y":197},
            "size":{
              "width":274,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6018969eabb4c258214aff276e5b4ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":98,
                  "y":197},
                "size":{
                  "width":274,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/details/u11.png"}},
{
          "id":"df0630735d6a4c01a515feee2902675c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00FF00},
            "location":{
              "x":98,
              "y":197},
            "size":{
              "width":225,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ac245ba956846a2a13d316cb1e4295f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FF00},
                "location":{
                  "x":98,
                  "y":197},
                "size":{
                  "width":225,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/details/u13.png"}},
{
          "id":"8ef8ea26a2cc472d8d68393b3bd88687",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":200,
              "y":197},
            "size":{
              "width":114,
              "height":13},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"653110a1ba964dd2a998c473845e1166",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":200,
                  "y":197},
                "size":{
                  "width":114,
                  "height":13},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d4e2afe8b12d4b4bb50a8200eb994f39",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":81,
              "y":77},
            "size":{
              "width":55,
              "height":24},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdb3bdd32aa74095a18b1599e4cabce9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":81,
                  "y":77},
                "size":{
                  "width":55,
                  "height":24},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Both labs in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"both_labs.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/lp_labs/u66.png"}},
{
          "id":"60a5c722fc804f638ab4e599fb2b7c14",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":146,
              "y":77},
            "size":{
              "width":69,
              "height":22}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"ee98e688fd1f4ddf847073aef928223f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":98,
              "y":165},
            "size":{
              "width":150,
              "height":22},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6835f912d6a4930b1c7c7b4d18cb8cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":98,
                  "y":165},
                "size":{
                  "width":150,
                  "height":22},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ca7464707c614a90897b5172cf4c6bc9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":98,
              "y":220},
            "size":{
              "width":83,
              "height":83},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e75662d06d4e403393049d35bb18b444",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":98,
                  "y":220},
                "size":{
                  "width":83,
                  "height":83},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/details/u22.png"}},
{
          "id":"4129fb6b56df4a5cb97486b778820aa5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":220},
            "size":{
              "width":150,
              "height":80},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b71010a932214e2f91a3748af3a855dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":220},
                "size":{
                  "width":150,
                  "height":80},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"10216e44826f4daeb0127062184a4e9e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":93,
              "y":313},
            "size":{
              "width":94,
              "height":34}},
          "adaptiveStyles":{
}},
{
          "id":"12338a7ba99b4c378af99db6658c7758",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"bold",
            "location":{
              "x":93,
              "y":357},
            "size":{
              "width":201,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfeb51a3f786475691dc927486e5b241",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"bold",
                "location":{
                  "x":93,
                  "y":357},
                "size":{
                  "width":201,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf541b645b724a2bb5f33e7ea232ab60",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":106,
              "y":383},
            "size":{
              "width":150,
              "height":80},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26494373dd794867a93835a7fe0ef2f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":106,
                  "y":383},
                "size":{
                  "width":150,
                  "height":80},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b4bb0cfce391475d9ea299d53b8d1ba3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":266,
              "y":383},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a586f05ff604a2d906fbda7603b0126",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":266,
                  "y":383},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b35eda2a4c2b4e7da8e35e9798c14448",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":453,
              "y":383},
            "size":{
              "width":150,
              "height":112},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"edc7ed2acf86482b8890848355cc81e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":453,
                  "y":383},
                "size":{
                  "width":150,
                  "height":112},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d0f3120b9f1412ab919763d82d22161",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":453,
              "y":197},
            "size":{
              "width":150,
              "height":96},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d31230fd5ac24ec285e6f6e4425b726b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":453,
                  "y":197},
                "size":{
                  "width":150,
                  "height":96},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "8d5404b131b34533ade63c7ae8d0cf0d":{
      "scriptId":"u0"},
    "5f3684c1de484b7da06d1e464b5d97fc":{
      "scriptId":"u1"},
    "548d2dab575e4205b303b3cef1d2882e":{
      "scriptId":"u2"},
    "040e7edb47a84a21bf89ac191524feb3":{
      "scriptId":"u3"},
    "73d041bc92ef4124be3167f7984aa03b":{
      "scriptId":"u4"},
    "7f5445df073347b0a98f91659f9d0dde":{
      "scriptId":"u5"},
    "2f3c6af3ce8f46e1b72bddd28955cc74":{
      "scriptId":"u6"},
    "6ebf42b8033241b4bec0ed5bad133ce8":{
      "scriptId":"u7"},
    "0110cb41f05442c4a46e059ea9ecd42c":{
      "scriptId":"u8"},
    "d4eafe12bb3847f4a9e4a94ee3ae6bcf":{
      "scriptId":"u9"},
    "fb20245f34084c888a0802942f8daa1b":{
      "scriptId":"u10"},
    "c247b10a3d004e2bacf143a11874bb77":{
      "scriptId":"u11"},
    "a6018969eabb4c258214aff276e5b4ba":{
      "scriptId":"u12"},
    "df0630735d6a4c01a515feee2902675c":{
      "scriptId":"u13"},
    "4ac245ba956846a2a13d316cb1e4295f":{
      "scriptId":"u14"},
    "8ef8ea26a2cc472d8d68393b3bd88687":{
      "scriptId":"u15"},
    "653110a1ba964dd2a998c473845e1166":{
      "scriptId":"u16"},
    "d4e2afe8b12d4b4bb50a8200eb994f39":{
      "scriptId":"u17"},
    "bdb3bdd32aa74095a18b1599e4cabce9":{
      "scriptId":"u18"},
    "60a5c722fc804f638ab4e599fb2b7c14":{
      "scriptId":"u19"},
    "ee98e688fd1f4ddf847073aef928223f":{
      "scriptId":"u20"},
    "b6835f912d6a4930b1c7c7b4d18cb8cc":{
      "scriptId":"u21"},
    "ca7464707c614a90897b5172cf4c6bc9":{
      "scriptId":"u22"},
    "e75662d06d4e403393049d35bb18b444":{
      "scriptId":"u23"},
    "4129fb6b56df4a5cb97486b778820aa5":{
      "scriptId":"u24"},
    "b71010a932214e2f91a3748af3a855dd":{
      "scriptId":"u25"},
    "10216e44826f4daeb0127062184a4e9e":{
      "scriptId":"u26"},
    "12338a7ba99b4c378af99db6658c7758":{
      "scriptId":"u27"},
    "bfeb51a3f786475691dc927486e5b241":{
      "scriptId":"u28"},
    "cf541b645b724a2bb5f33e7ea232ab60":{
      "scriptId":"u29"},
    "26494373dd794867a93835a7fe0ef2f9":{
      "scriptId":"u30"},
    "b4bb0cfce391475d9ea299d53b8d1ba3":{
      "scriptId":"u31"},
    "3a586f05ff604a2d906fbda7603b0126":{
      "scriptId":"u32"},
    "b35eda2a4c2b4e7da8e35e9798c14448":{
      "scriptId":"u33"},
    "edc7ed2acf86482b8890848355cc81e0":{
      "scriptId":"u34"},
    "8d0f3120b9f1412ab919763d82d22161":{
      "scriptId":"u35"},
    "d31230fd5ac24ec285e6f6e4425b726b":{
      "scriptId":"u36"}}});