$axure.loadCurrentPage({
  "url":"lp_labs.html",
  "generationDate":new Date(1397006830468.93),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"bc094da709be42439ade59791733c5af",
    "type":"Axure:Page",
    "name":"LP labs",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1c363b8da25e4782bca6f6b21f4324ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":61,
              "y":29},
            "size":{
              "width":361,
              "height":555},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c7a6aa8019741e589efd0c83b271b34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":61,
                  "y":29},
                "size":{
                  "width":361,
                  "height":555},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"906bc191f7c84ea681ac39aad0726ee9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":77,
              "y":68},
            "size":{
              "width":325,
              "height":429},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"936f33fb0f4f4aa1b0fa7cb627a7b048",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":77,
                  "y":68},
                "size":{
                  "width":325,
                  "height":429},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lp_labs/u2.png"}},
{
          "id":"b29beb480e3349a6baa9698c8dd1d5a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":214,
              "y":516},
            "size":{
              "width":52,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5dcdfad6842a41299b0d4da51a14bd64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":214,
                  "y":516},
                "size":{
                  "width":52,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"13d72a6abae0424f8b12a756cb8ac2a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":77,
              "y":68},
            "size":{
              "width":325,
              "height":87}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32026604277d435387b1f7addee5e57b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":77,
                  "y":68},
                "size":{
                  "width":325,
                  "height":87}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lp_labs/u6.png"}},
{
          "id":"a458c6b2d44e45e39f126f543d619351",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":327,
              "y":77},
            "size":{
              "width":69,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"4a3499c1c939434da5dab0c23588cbb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":164,
              "y":122},
            "size":{
              "width":150,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b4fab779ddf4d4e986662b95f102373",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":164,
                  "y":122},
                "size":{
                  "width":150,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e943515b89d44a299debd1a71b41ae63",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFF0099CC},
            "location":{
              "x":77,
              "y":165},
            "size":{
              "width":325,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"131fe32643bd4c759050b6cc91af3c38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099CC},
                "location":{
                  "x":77,
                  "y":165},
                "size":{
                  "width":325,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open LP labs in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"lp_labs.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/lp_labs/u11.png"}},
{
          "id":"da4e432770ea4a82af17fe63b92d32c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":87,
              "y":198},
            "size":{
              "width":303,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f862979c282f4d53a61ec8ca6d1b62cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":87,
                  "y":198},
                "size":{
                  "width":303,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lp_labs/u13.png"}},
{
          "id":"03b08186793c489a9a0de1ad400395a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":97,
              "y":203},
            "size":{
              "width":134,
              "height":13},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2ae4bde969841c6b854a62144c86db5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":97,
                  "y":203},
                "size":{
                  "width":134,
                  "height":13},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"906f10161aec4c17b510019f99dd2f2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":239,
              "y":206},
            "size":{
              "width":81,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cecd7c4252f40658e500c2b732f9792",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":239,
                  "y":206},
                "size":{
                  "width":81,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lp_labs/u17.png"}},
{
          "id":"e1bd1c4634fd4eeaa98a5691cf9ddab7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00FF00},
            "location":{
              "x":239,
              "y":206},
            "size":{
              "width":55,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee9495403633478093bf37811dd1d9f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FF00},
                "location":{
                  "x":239,
                  "y":206},
                "size":{
                  "width":55,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lp_labs/u19.png"}},
{
          "id":"985a10ca39ee4f7ba499dc69a33f6d8f",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":352,
              "y":203},
            "size":{
              "width":32,
              "height":21}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Details in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"details.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"8d185a7ab31648538eba32717b8fc814",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":87,
              "y":234},
            "size":{
              "width":303,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d6e8f602be045749288f4639388ab74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":87,
                  "y":234},
                "size":{
                  "width":303,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lp_labs/u13.png"}},
{
          "id":"65e407b3e0fd496c9562cecfdb8dd6fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":97,
              "y":238},
            "size":{
              "width":134,
              "height":13},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"235107142ff345e3ad34c6a115b95ff6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":97,
                  "y":238},
                "size":{
                  "width":134,
                  "height":13},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7efb643f65864b5facbfe8add239f4eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":239,
              "y":242},
            "size":{
              "width":81,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af81681a99464ea7b9d9d7ae86d42e47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":239,
                  "y":242},
                "size":{
                  "width":81,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lp_labs/u17.png"}},
{
          "id":"57e9a2998537462d8a4445fcb206c72e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00FF00},
            "location":{
              "x":239,
              "y":242},
            "size":{
              "width":55,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44891184287d44fe9fbbd4263f1ddc3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FF00},
                "location":{
                  "x":239,
                  "y":242},
                "size":{
                  "width":55,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lp_labs/u19.png"}},
{
          "id":"3d1c802bc2574c76ab5516e56ecd1e67",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":87,
              "y":270},
            "size":{
              "width":303,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"288cbcf522dc4726bcf095fb89812d09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":87,
                  "y":270},
                "size":{
                  "width":303,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lp_labs/u13.png"}},
{
          "id":"1b826bedbc46487ca031b06cf66aefc8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":97,
              "y":275},
            "size":{
              "width":134,
              "height":13},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c1c78fbb359458bb7d2e866bfea6744",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":97,
                  "y":275},
                "size":{
                  "width":134,
                  "height":13},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"949577fff3344a8cbff9e745b45e38d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":239,
              "y":278},
            "size":{
              "width":81,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba71cf67c8fe444fabaed90fbecdec58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":239,
                  "y":278},
                "size":{
                  "width":81,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lp_labs/u17.png"}},
{
          "id":"602461a19e9e4f4c960fba0206c4280e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00FF00},
            "location":{
              "x":239,
              "y":278},
            "size":{
              "width":55,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43ac6036757243ab91d0253d0c38b1ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FF00},
                "location":{
                  "x":239,
                  "y":278},
                "size":{
                  "width":55,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lp_labs/u19.png"}},
{
          "id":"c9c641c301394cefb42bd13aaadde590",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":87,
              "y":306},
            "size":{
              "width":303,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ffd91ec29ca47a5b649371c60795109",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":87,
                  "y":306},
                "size":{
                  "width":303,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lp_labs/u13.png"}},
{
          "id":"52bace4c99ab4b34a8d46debfcca9056",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":97,
              "y":310},
            "size":{
              "width":134,
              "height":13},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1dd16c4c2d24f7e8773af62f95b3296",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":97,
                  "y":310},
                "size":{
                  "width":134,
                  "height":13},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"486ae793d63d4c0cb71d671eea78f3bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":239,
              "y":315},
            "size":{
              "width":81,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"494b4d5ae772430181d283da7e8a12d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":239,
                  "y":315},
                "size":{
                  "width":81,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lp_labs/u17.png"}},
{
          "id":"eea772d4dbc14ab68b9569a2ba7846aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00FF00},
            "location":{
              "x":239,
              "y":315},
            "size":{
              "width":55,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"253e949444234d9096c8dfdf04d7c6c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FF00},
                "location":{
                  "x":239,
                  "y":315},
                "size":{
                  "width":55,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lp_labs/u19.png"}},
{
          "id":"bbce57a6199a4d20b6d5aa0382ebccee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":87,
              "y":342},
            "size":{
              "width":303,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c401c2ef996440c3b2b4baee2e0ad69d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":87,
                  "y":342},
                "size":{
                  "width":303,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lp_labs/u13.png"}},
{
          "id":"a29e4681ea274dd1a993a15a658b334f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":97,
              "y":346},
            "size":{
              "width":134,
              "height":13},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42647f184f754801921d9c5001d71380",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":97,
                  "y":346},
                "size":{
                  "width":134,
                  "height":13},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"08e75ec3e63a40fc8382f184cc73a630",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":239,
              "y":351},
            "size":{
              "width":81,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09add4e4c3d2450f943ea53b39af9e8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":239,
                  "y":351},
                "size":{
                  "width":81,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lp_labs/u17.png"}},
{
          "id":"615944d84ceb445ca6350bd44ee3530b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00FF00},
            "location":{
              "x":239,
              "y":351},
            "size":{
              "width":55,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"146eb53a7abf449da74a1f0afcb1e28d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FF00},
                "location":{
                  "x":239,
                  "y":351},
                "size":{
                  "width":55,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lp_labs/u19.png"}},
{
          "id":"be2391ab05c9400fbda59ba8afb209bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":265,
              "y":206},
            "size":{
              "width":30,
              "height":13},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"818013c84a7b4c1a8b0539a14b92dceb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":265,
                  "y":206},
                "size":{
                  "width":30,
                  "height":13},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4eadf90002e541148bf18315dab898d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":264,
              "y":242},
            "size":{
              "width":30,
              "height":13},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"906f475fc9604bc2b6ff38f3bf203cbb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":264,
                  "y":242},
                "size":{
                  "width":30,
                  "height":13},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"35e46cabb1c641bba54d53dade2f6fbf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":264,
              "y":278},
            "size":{
              "width":30,
              "height":13},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3b0240d16974cf9b10995595732fcca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":264,
                  "y":278},
                "size":{
                  "width":30,
                  "height":13},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f55bc10ad0584822b80e829061d8c6c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":264,
              "y":315},
            "size":{
              "width":30,
              "height":13},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d49a2b3e4a5473ca089965228a33b43",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":264,
                  "y":315},
                "size":{
                  "width":30,
                  "height":13},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c386cb1f5e0e406ebf4976794da639c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":264,
              "y":351},
            "size":{
              "width":30,
              "height":13},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ae421a828414b84b2438f9791f22739",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":264,
                  "y":351},
                "size":{
                  "width":30,
                  "height":13},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65d49a4f003040ea8e46735afd0d8acf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":77,
              "y":381},
            "size":{
              "width":325,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89d52f60cfbc4a8aa39296eb7462128e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":77,
                  "y":381},
                "size":{
                  "width":325,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Loop labs in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"loop_labs.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/lp_labs/u64.png"}},
{
          "id":"9d1a77e2d9cb4bcc83c2c123edf9be3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":81,
              "y":77},
            "size":{
              "width":55,
              "height":24},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5aa2673cdbb4f45a02e3de1d31c5f8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":81,
                  "y":77},
                "size":{
                  "width":55,
                  "height":24},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/lp_labs/u66.png"}},
{
          "id":"eaf41f24a595414aa50ea718d46ee2d7",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":146,
              "y":77},
            "size":{
              "width":69,
              "height":22}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"3ec6f0bcc091486d99a0e4d7bec3d754",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":352,
              "y":238},
            "size":{
              "width":32,
              "height":21}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Details in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"details.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"744fd7744d40457aaa891d6e4c76ad5b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":352,
              "y":274},
            "size":{
              "width":32,
              "height":21}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Details in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"details.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"4cd6c5f67df84df2ba6e48d31ada2e7e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":352,
              "y":311},
            "size":{
              "width":32,
              "height":21}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Details in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"details.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"2699c11944aa47c1b99ddf0313dd7654",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":352,
              "y":346.5},
            "size":{
              "width":32,
              "height":21}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Details in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"details.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "1c363b8da25e4782bca6f6b21f4324ee":{
      "scriptId":"u0"},
    "6c7a6aa8019741e589efd0c83b271b34":{
      "scriptId":"u1"},
    "906bc191f7c84ea681ac39aad0726ee9":{
      "scriptId":"u2"},
    "936f33fb0f4f4aa1b0fa7cb627a7b048":{
      "scriptId":"u3"},
    "b29beb480e3349a6baa9698c8dd1d5a6":{
      "scriptId":"u4"},
    "5dcdfad6842a41299b0d4da51a14bd64":{
      "scriptId":"u5"},
    "13d72a6abae0424f8b12a756cb8ac2a5":{
      "scriptId":"u6"},
    "32026604277d435387b1f7addee5e57b":{
      "scriptId":"u7"},
    "a458c6b2d44e45e39f126f543d619351":{
      "scriptId":"u8"},
    "4a3499c1c939434da5dab0c23588cbb4":{
      "scriptId":"u9"},
    "6b4fab779ddf4d4e986662b95f102373":{
      "scriptId":"u10"},
    "e943515b89d44a299debd1a71b41ae63":{
      "scriptId":"u11"},
    "131fe32643bd4c759050b6cc91af3c38":{
      "scriptId":"u12"},
    "da4e432770ea4a82af17fe63b92d32c8":{
      "scriptId":"u13"},
    "f862979c282f4d53a61ec8ca6d1b62cd":{
      "scriptId":"u14"},
    "03b08186793c489a9a0de1ad400395a9":{
      "scriptId":"u15"},
    "b2ae4bde969841c6b854a62144c86db5":{
      "scriptId":"u16"},
    "906f10161aec4c17b510019f99dd2f2c":{
      "scriptId":"u17"},
    "3cecd7c4252f40658e500c2b732f9792":{
      "scriptId":"u18"},
    "e1bd1c4634fd4eeaa98a5691cf9ddab7":{
      "scriptId":"u19"},
    "ee9495403633478093bf37811dd1d9f0":{
      "scriptId":"u20"},
    "985a10ca39ee4f7ba499dc69a33f6d8f":{
      "scriptId":"u21"},
    "8d185a7ab31648538eba32717b8fc814":{
      "scriptId":"u22"},
    "2d6e8f602be045749288f4639388ab74":{
      "scriptId":"u23"},
    "65e407b3e0fd496c9562cecfdb8dd6fb":{
      "scriptId":"u24"},
    "235107142ff345e3ad34c6a115b95ff6":{
      "scriptId":"u25"},
    "7efb643f65864b5facbfe8add239f4eb":{
      "scriptId":"u26"},
    "af81681a99464ea7b9d9d7ae86d42e47":{
      "scriptId":"u27"},
    "57e9a2998537462d8a4445fcb206c72e":{
      "scriptId":"u28"},
    "44891184287d44fe9fbbd4263f1ddc3a":{
      "scriptId":"u29"},
    "3d1c802bc2574c76ab5516e56ecd1e67":{
      "scriptId":"u30"},
    "288cbcf522dc4726bcf095fb89812d09":{
      "scriptId":"u31"},
    "1b826bedbc46487ca031b06cf66aefc8":{
      "scriptId":"u32"},
    "8c1c78fbb359458bb7d2e866bfea6744":{
      "scriptId":"u33"},
    "949577fff3344a8cbff9e745b45e38d5":{
      "scriptId":"u34"},
    "ba71cf67c8fe444fabaed90fbecdec58":{
      "scriptId":"u35"},
    "602461a19e9e4f4c960fba0206c4280e":{
      "scriptId":"u36"},
    "43ac6036757243ab91d0253d0c38b1ba":{
      "scriptId":"u37"},
    "c9c641c301394cefb42bd13aaadde590":{
      "scriptId":"u38"},
    "4ffd91ec29ca47a5b649371c60795109":{
      "scriptId":"u39"},
    "52bace4c99ab4b34a8d46debfcca9056":{
      "scriptId":"u40"},
    "e1dd16c4c2d24f7e8773af62f95b3296":{
      "scriptId":"u41"},
    "486ae793d63d4c0cb71d671eea78f3bc":{
      "scriptId":"u42"},
    "494b4d5ae772430181d283da7e8a12d4":{
      "scriptId":"u43"},
    "eea772d4dbc14ab68b9569a2ba7846aa":{
      "scriptId":"u44"},
    "253e949444234d9096c8dfdf04d7c6c6":{
      "scriptId":"u45"},
    "bbce57a6199a4d20b6d5aa0382ebccee":{
      "scriptId":"u46"},
    "c401c2ef996440c3b2b4baee2e0ad69d":{
      "scriptId":"u47"},
    "a29e4681ea274dd1a993a15a658b334f":{
      "scriptId":"u48"},
    "42647f184f754801921d9c5001d71380":{
      "scriptId":"u49"},
    "08e75ec3e63a40fc8382f184cc73a630":{
      "scriptId":"u50"},
    "09add4e4c3d2450f943ea53b39af9e8d":{
      "scriptId":"u51"},
    "615944d84ceb445ca6350bd44ee3530b":{
      "scriptId":"u52"},
    "146eb53a7abf449da74a1f0afcb1e28d":{
      "scriptId":"u53"},
    "be2391ab05c9400fbda59ba8afb209bc":{
      "scriptId":"u54"},
    "818013c84a7b4c1a8b0539a14b92dceb":{
      "scriptId":"u55"},
    "4eadf90002e541148bf18315dab898d8":{
      "scriptId":"u56"},
    "906f475fc9604bc2b6ff38f3bf203cbb":{
      "scriptId":"u57"},
    "35e46cabb1c641bba54d53dade2f6fbf":{
      "scriptId":"u58"},
    "e3b0240d16974cf9b10995595732fcca":{
      "scriptId":"u59"},
    "f55bc10ad0584822b80e829061d8c6c3":{
      "scriptId":"u60"},
    "1d49a2b3e4a5473ca089965228a33b43":{
      "scriptId":"u61"},
    "c386cb1f5e0e406ebf4976794da639c8":{
      "scriptId":"u62"},
    "4ae421a828414b84b2438f9791f22739":{
      "scriptId":"u63"},
    "65d49a4f003040ea8e46735afd0d8acf":{
      "scriptId":"u64"},
    "89d52f60cfbc4a8aa39296eb7462128e":{
      "scriptId":"u65"},
    "9d1a77e2d9cb4bcc83c2c123edf9be3e":{
      "scriptId":"u66"},
    "d5aa2673cdbb4f45a02e3de1d31c5f8e":{
      "scriptId":"u67"},
    "eaf41f24a595414aa50ea718d46ee2d7":{
      "scriptId":"u68"},
    "3ec6f0bcc091486d99a0e4d7bec3d754":{
      "scriptId":"u69"},
    "744fd7744d40457aaa891d6e4c76ad5b":{
      "scriptId":"u70"},
    "4cd6c5f67df84df2ba6e48d31ada2e7e":{
      "scriptId":"u71"},
    "2699c11944aa47c1b99ddf0313dd7654":{
      "scriptId":"u72"}}});