$axure.loadCurrentPage({
  "url":"student_activities.html",
  "generationDate":new Date(1396931400715.29),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5ecaa0ba1dd64b9995cce7894ab5e730",
    "type":"Axure:Page",
    "name":"Student Activities",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8d8c1a0720544d31ab4b541b3cf00cde",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":313,
              "y":197.5},
            "size":{
              "width":180,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"c25f8d2feea2426db485370d80e0fe93",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Italic', 'Arial'",
            "fontStyle":"italic",
            "location":{
              "x":516,
              "y":195},
            "size":{
              "width":229,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f11018ec61c04050a5ee12eb37675f04",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":239},
            "size":{
              "width":350,
              "height":189}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd690a22a1df47ed9ea8c7f1e3d6d382",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":239},
                "size":{
                  "width":350,
                  "height":189}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/student_activities/u2.png"}},
{
          "id":"31da69b7ed6e4e97892360fc369e53fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":452},
            "size":{
              "width":350,
              "height":189}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf1f78c5fbf647a4ab42ae7d0e697a71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":452},
                "size":{
                  "width":350,
                  "height":189}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/student_activities/u2.png"}},
{
          "id":"a533ccae28164cad8809e35a20136aa7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":667},
            "size":{
              "width":350,
              "height":189}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5830d83e8fc84a4ea416eb4fa86fe687",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":667},
                "size":{
                  "width":350,
                  "height":189}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/student_activities/u2.png"}},
{
          "id":"fcb3d0046ccf429cae3779607f315da9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":1102},
            "size":{
              "width":622,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55e7edafaf154408830902fbc8a1fb83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":1102},
                "size":{
                  "width":622,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/student_activities/u8.png"}},
{
          "id":"f0f60a3c03274222891e901cafe3f14d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":424,
              "y":239},
            "size":{
              "width":321,
              "height":264}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"841d05ae8a5745a8b76b69adaa91d34d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":424,
                  "y":239},
                "size":{
                  "width":321,
                  "height":264}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/student_activities/u10.png"}},
{
          "id":"dbde45a8d5ce48ce92130f56d41eeede",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":442,
              "y":247},
            "size":{
              "width":226,
              "height":22},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1b6ef30ffa74f838e311b6ba0dffba7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":442,
                  "y":247},
                "size":{
                  "width":226,
                  "height":22},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3023ff2346a74504823e8abe7546fc44",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":442,
              "y":279},
            "size":{
              "width":87,
              "height":66},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e4ed471fcd14ed9a44030bae2aa96c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":442,
                  "y":279},
                "size":{
                  "width":87,
                  "height":66},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/student_activities/u14.png"}},
{
          "id":"6eb5cf6f3d2144deba3254ab5b91b0d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":537,
              "y":279},
            "size":{
              "width":178,
              "height":32},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce2799e7e73640a795657b56e47bcb03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":537,
                  "y":279},
                "size":{
                  "width":178,
                  "height":32},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cbe32c61694842819ea61cda496db42d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":890},
            "size":{
              "width":350,
              "height":189}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcae422f8c8640699fe973711ab25abd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":890},
                "size":{
                  "width":350,
                  "height":189}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/student_activities/u2.png"}},
{
          "id":"a584addec6054e1c955c19f4a338c757",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":424,
              "y":516},
            "size":{
              "width":321,
              "height":125}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f95c8e76c06241c298f605883a175364",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":424,
                  "y":516},
                "size":{
                  "width":321,
                  "height":125}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/student_activities/u20.png"}},
{
          "id":"a249cba37dbe4ecb901018edfd2fca9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":424,
              "y":651},
            "size":{
              "width":321,
              "height":125}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcb42fe2a6bf45b7b1663b5daecbabc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":424,
                  "y":651},
                "size":{
                  "width":321,
                  "height":125}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/student_activities/u20.png"}},
{
          "id":"5dba8b05df554a30849b8e725553e506",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":239},
            "size":{
              "width":150,
              "height":110},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b961fcc17bb24619ab140040a8372eda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":239},
                "size":{
                  "width":150,
                  "height":110},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"6608c5bcd6244358a7e0f14394700770",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":349},
            "size":{
              "width":150,
              "height":78},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17f715c6e7034ab88c556389c9e4467d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":349},
                "size":{
                  "width":150,
                  "height":78},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"a5c12dab312b48f3af558acfc722de4f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":267,
              "y":239},
            "size":{
              "width":109,
              "height":57},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ba7141c1068457ab8b29ff6aaff215e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":267,
                  "y":239},
                "size":{
                  "width":109,
                  "height":57},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"ff322459e3e94d618d87d5b603368a57",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":267,
              "y":296},
            "size":{
              "width":109,
              "height":85},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a9094f4d3e948a9a8e0d91a7dfccaed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":267,
                  "y":296},
                "size":{
                  "width":109,
                  "height":85},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"cf973c9bed164c6ab0d20660b258a2ed",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":176,
              "y":381},
            "size":{
              "width":200,
              "height":47},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c102bec3dacd4e8eab2405c3028a1721",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":176,
                  "y":381},
                "size":{
                  "width":200,
                  "height":47},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"8461c9aa090f4e88a24c79e48bb8d4fe",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":176,
              "y":239},
            "size":{
              "width":91,
              "height":142},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b19f65e6d5de4cdd8ee8323920a24a22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":176,
                  "y":239},
                "size":{
                  "width":91,
                  "height":142},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"f2e56e02bb9343189dcbd66fa58e6f46",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":312},
            "size":{
              "width":231,
              "height":59}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9cf7a9f95ff84f6a83df6a5fb364cf6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":312},
                "size":{
                  "width":231,
                  "height":59}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Student Profile in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"student_profile.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/student_activities/u36.png"}},
{
          "id":"e0b5b47e93774aa4a58926ec588c5443",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":452},
            "size":{
              "width":150,
              "height":110},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f69630c9fd744ad995f38c28d2d57c6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":452},
                "size":{
                  "width":150,
                  "height":110},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"e0dd698d34fb47d4a17467fb25c4fc9b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":562},
            "size":{
              "width":150,
              "height":78},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12978f331e39448789bff512ce285025",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":562},
                "size":{
                  "width":150,
                  "height":78},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"5c2a153bad7749ca989733484ea19ab7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":267,
              "y":452},
            "size":{
              "width":109,
              "height":57},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd8bdc18297748529fcb8950122f5035",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":267,
                  "y":452},
                "size":{
                  "width":109,
                  "height":57},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"53e4180637264b1a8449bce04a7edfc4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":267,
              "y":509},
            "size":{
              "width":109,
              "height":85},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e403310b8ff4eb69187bfcae606aa1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":267,
                  "y":509},
                "size":{
                  "width":109,
                  "height":85},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"28153ea9c0e94041bc239fdbccb9af23",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":176,
              "y":594},
            "size":{
              "width":200,
              "height":47},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2151173aea7a4ecc8f85de146f2b600b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":176,
                  "y":594},
                "size":{
                  "width":200,
                  "height":47},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"77798788222045dcb432e5e185f706b8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":176,
              "y":452},
            "size":{
              "width":91,
              "height":142},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6710590647c4d29bba3c937b9abad45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":176,
                  "y":452},
                "size":{
                  "width":91,
                  "height":142},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"8e3793534b00458ea7c2832d46f44482",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":525},
            "size":{
              "width":231,
              "height":59}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"066e3958e2a54112bad17a70d2455dbc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":525},
                "size":{
                  "width":231,
                  "height":59}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Student Profile in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"student_profile.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/student_activities/u36.png"}},
{
          "id":"9b10d6c0a38c41fa8d358f3991ebc139",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":667},
            "size":{
              "width":150,
              "height":110},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61dc873920a4464797d0e2f7321c7155",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":667},
                "size":{
                  "width":150,
                  "height":110},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"ec386c8eb1a446bb811b0469a13a76a1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":777},
            "size":{
              "width":150,
              "height":78},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2064df5e030743f7891e029dd65a0ae9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":777},
                "size":{
                  "width":150,
                  "height":78},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"530986a9807343a3aa1fbafccb3abe87",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":267,
              "y":667},
            "size":{
              "width":109,
              "height":57},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"958b0a2686cb4698933c9d32086a795b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":267,
                  "y":667},
                "size":{
                  "width":109,
                  "height":57},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"373588b649944bcaa1dfb2e4e4488e55",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":267,
              "y":724},
            "size":{
              "width":109,
              "height":85},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1e28304153443358001199c97610cfd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":267,
                  "y":724},
                "size":{
                  "width":109,
                  "height":85},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"bc662c38980d4133ab51d3774d10b969",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":176,
              "y":809},
            "size":{
              "width":200,
              "height":47},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5207d5d66f8403484afea700c7763da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":176,
                  "y":809},
                "size":{
                  "width":200,
                  "height":47},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"35f06955b8de4f85b384f4cda89fc0c3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":176,
              "y":667},
            "size":{
              "width":91,
              "height":142},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1f110fec59943449c1013edbb51da40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":176,
                  "y":667},
                "size":{
                  "width":91,
                  "height":142},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"bf5f5047290d44ac8f99b355e805ace9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":740},
            "size":{
              "width":231,
              "height":59}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30dab298177e4ca89dc6e5c6ed276cca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":740},
                "size":{
                  "width":231,
                  "height":59}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Student Profile in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"student_profile.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/student_activities/u36.png"}},
{
          "id":"3929e2a1fc714202afb07887fa1d9022",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":890},
            "size":{
              "width":150,
              "height":110},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7b5872998e34b0b9601760a7f5c69dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":890},
                "size":{
                  "width":150,
                  "height":110},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"05be7c54d5ee4c88862f180986f93846",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":1000},
            "size":{
              "width":150,
              "height":78},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a237e4852ea4f7392a0d3ecd350af85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":1000},
                "size":{
                  "width":150,
                  "height":78},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"cb484b27de954c40b1a054c6d0fb23a2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":267,
              "y":890},
            "size":{
              "width":109,
              "height":57},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43a3d5cc65e74a3fb26cb052578e589b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":267,
                  "y":890},
                "size":{
                  "width":109,
                  "height":57},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"ef6fee763a5a40b8b4f2c6bc792192e3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":267,
              "y":947},
            "size":{
              "width":109,
              "height":85},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0992cb5cafb3469b9d103632e38b05ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":267,
                  "y":947},
                "size":{
                  "width":109,
                  "height":85},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"a7ef48bdaeae4eb4b2571d851936d465",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":176,
              "y":1032},
            "size":{
              "width":200,
              "height":47},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e43ea27de3e466a998f951a38e684f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":176,
                  "y":1032},
                "size":{
                  "width":200,
                  "height":47},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"6ca1498bee434d48bb40a4881eded868",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":176,
              "y":890},
            "size":{
              "width":91,
              "height":142},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5be93df339394234833f6461b15c3373",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":176,
                  "y":890},
                "size":{
                  "width":91,
                  "height":142},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"ab8739fdf38343b48c5faef911e4ca7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":963},
            "size":{
              "width":231,
              "height":59}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5a1e1ec77bd4af6b1a68926f7b773ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":963},
                "size":{
                  "width":231,
                  "height":59}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Student Profile in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"student_profile.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/student_activities/u36.png"}},
{
          "id":"5d447c4ec9bc443a9896ccf09da0c5c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":13},
            "size":{
              "width":231,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd84c61e242847ce8b25262da1c66b6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":13},
                "size":{
                  "width":231,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"3e25c94b7d8942e48660fd66f90f39d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":123},
            "size":{
              "width":195,
              "height":52},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15e6587cc1a84d098ef3e080a9545aef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":123},
                "size":{
                  "width":195,
                  "height":52},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open News in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"news.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"b9d466027bca427aad4b3e57e0bc94fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":208,
              "y":123},
            "size":{
              "width":195,
              "height":52},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e75d1c0a3ead41f084bdb7233da0cb3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":208,
                  "y":123},
                "size":{
                  "width":195,
                  "height":52},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 2",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Services in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"services.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"dffcbbc7474b4e619455726bea1c03e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":403,
              "y":123},
            "size":{
              "width":195,
              "height":52},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c0ce14fbe614cb081e27e0d83b5d7a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":403,
                  "y":123},
                "size":{
                  "width":195,
                  "height":52},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Student Activities in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"student_activities.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"0c3699f0c5d24e3a9a36c6feb1e8317a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":597,
              "y":123},
            "size":{
              "width":195,
              "height":52},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54c990e3f73d44208a712f32de37ab16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":597,
                  "y":123},
                "size":{
                  "width":195,
                  "height":52},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Portfolio in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"portfolio.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"e9ac1509891c477db3f03e6af474aae7",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":583,
              "y":74},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"248f51b026d8497d8556b63413404e1d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":175,
              "y":109},
            "size":{
              "width":23,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce567cb2ff834bf8b31c4c71b39f26fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":175,
                  "y":109},
                "size":{
                  "width":23,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC0000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u29.png"}},
{
          "id":"e4de9b34688d4c239885f8c92ee78420",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":597,
              "y":13},
            "size":{
              "width":208,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93bacb6333774aaa8f8e2a3b48900543",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":597,
                  "y":13},
                "size":{
                  "width":208,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a8a4e33e69b493aa3ed5e42a60a1b3f",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":196},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Student Activities in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"student_activities.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"77c0ddf742e14d1d8e17ee1dba4b6da2",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":136,
              "y":196},
            "size":{
              "width":155,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Clubs/Activities in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"clubs_activities.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "8d8c1a0720544d31ab4b541b3cf00cde":{
      "scriptId":"u0"},
    "c25f8d2feea2426db485370d80e0fe93":{
      "scriptId":"u1"},
    "f11018ec61c04050a5ee12eb37675f04":{
      "scriptId":"u2"},
    "dd690a22a1df47ed9ea8c7f1e3d6d382":{
      "scriptId":"u3"},
    "31da69b7ed6e4e97892360fc369e53fe":{
      "scriptId":"u4"},
    "cf1f78c5fbf647a4ab42ae7d0e697a71":{
      "scriptId":"u5"},
    "a533ccae28164cad8809e35a20136aa7":{
      "scriptId":"u6"},
    "5830d83e8fc84a4ea416eb4fa86fe687":{
      "scriptId":"u7"},
    "fcb3d0046ccf429cae3779607f315da9":{
      "scriptId":"u8"},
    "55e7edafaf154408830902fbc8a1fb83":{
      "scriptId":"u9"},
    "f0f60a3c03274222891e901cafe3f14d":{
      "scriptId":"u10"},
    "841d05ae8a5745a8b76b69adaa91d34d":{
      "scriptId":"u11"},
    "dbde45a8d5ce48ce92130f56d41eeede":{
      "scriptId":"u12"},
    "f1b6ef30ffa74f838e311b6ba0dffba7":{
      "scriptId":"u13"},
    "3023ff2346a74504823e8abe7546fc44":{
      "scriptId":"u14"},
    "9e4ed471fcd14ed9a44030bae2aa96c8":{
      "scriptId":"u15"},
    "6eb5cf6f3d2144deba3254ab5b91b0d2":{
      "scriptId":"u16"},
    "ce2799e7e73640a795657b56e47bcb03":{
      "scriptId":"u17"},
    "cbe32c61694842819ea61cda496db42d":{
      "scriptId":"u18"},
    "dcae422f8c8640699fe973711ab25abd":{
      "scriptId":"u19"},
    "a584addec6054e1c955c19f4a338c757":{
      "scriptId":"u20"},
    "f95c8e76c06241c298f605883a175364":{
      "scriptId":"u21"},
    "a249cba37dbe4ecb901018edfd2fca9c":{
      "scriptId":"u22"},
    "fcb42fe2a6bf45b7b1663b5daecbabc6":{
      "scriptId":"u23"},
    "5dba8b05df554a30849b8e725553e506":{
      "scriptId":"u24"},
    "b961fcc17bb24619ab140040a8372eda":{
      "scriptId":"u25"},
    "6608c5bcd6244358a7e0f14394700770":{
      "scriptId":"u26"},
    "17f715c6e7034ab88c556389c9e4467d":{
      "scriptId":"u27"},
    "a5c12dab312b48f3af558acfc722de4f":{
      "scriptId":"u28"},
    "5ba7141c1068457ab8b29ff6aaff215e":{
      "scriptId":"u29"},
    "ff322459e3e94d618d87d5b603368a57":{
      "scriptId":"u30"},
    "7a9094f4d3e948a9a8e0d91a7dfccaed":{
      "scriptId":"u31"},
    "cf973c9bed164c6ab0d20660b258a2ed":{
      "scriptId":"u32"},
    "c102bec3dacd4e8eab2405c3028a1721":{
      "scriptId":"u33"},
    "8461c9aa090f4e88a24c79e48bb8d4fe":{
      "scriptId":"u34"},
    "b19f65e6d5de4cdd8ee8323920a24a22":{
      "scriptId":"u35"},
    "f2e56e02bb9343189dcbd66fa58e6f46":{
      "scriptId":"u36"},
    "9cf7a9f95ff84f6a83df6a5fb364cf6c":{
      "scriptId":"u37"},
    "e0b5b47e93774aa4a58926ec588c5443":{
      "scriptId":"u38"},
    "f69630c9fd744ad995f38c28d2d57c6d":{
      "scriptId":"u39"},
    "e0dd698d34fb47d4a17467fb25c4fc9b":{
      "scriptId":"u40"},
    "12978f331e39448789bff512ce285025":{
      "scriptId":"u41"},
    "5c2a153bad7749ca989733484ea19ab7":{
      "scriptId":"u42"},
    "dd8bdc18297748529fcb8950122f5035":{
      "scriptId":"u43"},
    "53e4180637264b1a8449bce04a7edfc4":{
      "scriptId":"u44"},
    "3e403310b8ff4eb69187bfcae606aa1c":{
      "scriptId":"u45"},
    "28153ea9c0e94041bc239fdbccb9af23":{
      "scriptId":"u46"},
    "2151173aea7a4ecc8f85de146f2b600b":{
      "scriptId":"u47"},
    "77798788222045dcb432e5e185f706b8":{
      "scriptId":"u48"},
    "e6710590647c4d29bba3c937b9abad45":{
      "scriptId":"u49"},
    "8e3793534b00458ea7c2832d46f44482":{
      "scriptId":"u50"},
    "066e3958e2a54112bad17a70d2455dbc":{
      "scriptId":"u51"},
    "9b10d6c0a38c41fa8d358f3991ebc139":{
      "scriptId":"u52"},
    "61dc873920a4464797d0e2f7321c7155":{
      "scriptId":"u53"},
    "ec386c8eb1a446bb811b0469a13a76a1":{
      "scriptId":"u54"},
    "2064df5e030743f7891e029dd65a0ae9":{
      "scriptId":"u55"},
    "530986a9807343a3aa1fbafccb3abe87":{
      "scriptId":"u56"},
    "958b0a2686cb4698933c9d32086a795b":{
      "scriptId":"u57"},
    "373588b649944bcaa1dfb2e4e4488e55":{
      "scriptId":"u58"},
    "d1e28304153443358001199c97610cfd":{
      "scriptId":"u59"},
    "bc662c38980d4133ab51d3774d10b969":{
      "scriptId":"u60"},
    "a5207d5d66f8403484afea700c7763da":{
      "scriptId":"u61"},
    "35f06955b8de4f85b384f4cda89fc0c3":{
      "scriptId":"u62"},
    "e1f110fec59943449c1013edbb51da40":{
      "scriptId":"u63"},
    "bf5f5047290d44ac8f99b355e805ace9":{
      "scriptId":"u64"},
    "30dab298177e4ca89dc6e5c6ed276cca":{
      "scriptId":"u65"},
    "3929e2a1fc714202afb07887fa1d9022":{
      "scriptId":"u66"},
    "e7b5872998e34b0b9601760a7f5c69dc":{
      "scriptId":"u67"},
    "05be7c54d5ee4c88862f180986f93846":{
      "scriptId":"u68"},
    "0a237e4852ea4f7392a0d3ecd350af85":{
      "scriptId":"u69"},
    "cb484b27de954c40b1a054c6d0fb23a2":{
      "scriptId":"u70"},
    "43a3d5cc65e74a3fb26cb052578e589b":{
      "scriptId":"u71"},
    "ef6fee763a5a40b8b4f2c6bc792192e3":{
      "scriptId":"u72"},
    "0992cb5cafb3469b9d103632e38b05ed":{
      "scriptId":"u73"},
    "a7ef48bdaeae4eb4b2571d851936d465":{
      "scriptId":"u74"},
    "6e43ea27de3e466a998f951a38e684f1":{
      "scriptId":"u75"},
    "6ca1498bee434d48bb40a4881eded868":{
      "scriptId":"u76"},
    "5be93df339394234833f6461b15c3373":{
      "scriptId":"u77"},
    "ab8739fdf38343b48c5faef911e4ca7e":{
      "scriptId":"u78"},
    "d5a1e1ec77bd4af6b1a68926f7b773ad":{
      "scriptId":"u79"},
    "5d447c4ec9bc443a9896ccf09da0c5c4":{
      "scriptId":"u80"},
    "cd84c61e242847ce8b25262da1c66b6b":{
      "scriptId":"u81"},
    "3e25c94b7d8942e48660fd66f90f39d2":{
      "scriptId":"u82"},
    "15e6587cc1a84d098ef3e080a9545aef":{
      "scriptId":"u83"},
    "b9d466027bca427aad4b3e57e0bc94fe":{
      "scriptId":"u84"},
    "e75d1c0a3ead41f084bdb7233da0cb3f":{
      "scriptId":"u85"},
    "dffcbbc7474b4e619455726bea1c03e2":{
      "scriptId":"u86"},
    "8c0ce14fbe614cb081e27e0d83b5d7a6":{
      "scriptId":"u87"},
    "0c3699f0c5d24e3a9a36c6feb1e8317a":{
      "scriptId":"u88"},
    "54c990e3f73d44208a712f32de37ab16":{
      "scriptId":"u89"},
    "e9ac1509891c477db3f03e6af474aae7":{
      "scriptId":"u90"},
    "248f51b026d8497d8556b63413404e1d":{
      "scriptId":"u91"},
    "ce567cb2ff834bf8b31c4c71b39f26fd":{
      "scriptId":"u92"},
    "e4de9b34688d4c239885f8c92ee78420":{
      "scriptId":"u93"},
    "93bacb6333774aaa8f8e2a3b48900543":{
      "scriptId":"u94"},
    "2a8a4e33e69b493aa3ed5e42a60a1b3f":{
      "scriptId":"u95"},
    "77c0ddf742e14d1d8e17ee1dba4b6da2":{
      "scriptId":"u96"}}});