$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1396931400054.25),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"fd544d9a8df349008ce0f5f502d5e35e",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"345513e758cc4a9e902c8e10402b09fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":13},
            "size":{
              "width":231,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8580fb800fa24dfa850379cfee8108ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":13},
                "size":{
                  "width":231,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"eba8cd51a067435da12689193bb49f2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":69,
              "y":199},
            "size":{
              "width":211,
              "height":212}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9634558bb9ab4557b8a71e9729d4fed9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":69,
                  "y":199},
                "size":{
                  "width":211,
                  "height":212}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"c699867337a04b9797162aa6ca61f636",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":123},
            "size":{
              "width":195,
              "height":52},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0c71c7a6ff04861ab402e90f789f6e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":123},
                "size":{
                  "width":195,
                  "height":52},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open News in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"news.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"00545dd83eca4f26b060cc6cfdbdc8ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":208,
              "y":123},
            "size":{
              "width":195,
              "height":52},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47b1b31c5cf243ef8235bf7d0bdcb037",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":208,
                  "y":123},
                "size":{
                  "width":195,
                  "height":52},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 2",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Services in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"services.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"b31dc9cefcd74fee8e1685934661a70c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":403,
              "y":123},
            "size":{
              "width":195,
              "height":52},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f61d7d8de86409e969e551ffda75e4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":403,
                  "y":123},
                "size":{
                  "width":195,
                  "height":52},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Student Activities in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"student_activities.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"e969514d3d2e49e291bb396108c60a31",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":597,
              "y":123},
            "size":{
              "width":195,
              "height":52},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d16ef71ff4c4a7ca7a13731a20c54de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":597,
                  "y":123},
                "size":{
                  "width":195,
                  "height":52},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Portfolio in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"portfolio.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"e680ed0aa91a400cb2248480523eb426",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":583,
              "y":74},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"3e2c9c7f401c43d0b308fc737da37465",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":69,
              "y":421},
            "size":{
              "width":214,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1835cba8cf5c438ea51f80f60e21776d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":69,
                  "y":421},
                "size":{
                  "width":214,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u13.png"}},
{
          "id":"a600022e7f7d4b9e92fa032624b72dce",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":293,
              "y":421},
            "size":{
              "width":454,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a37a3c54d14d4e8bbd2de8892d25a94a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":293,
                  "y":421},
                "size":{
                  "width":454,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u15.png"}},
{
          "id":"858169ee9bde4f9d9fa44e78d80e1aff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":199},
            "size":{
              "width":457,
              "height":212}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c7213cf79b34a7b9e2cd76b3a3f249a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":290,
                  "y":199},
                "size":{
                  "width":457,
                  "height":212}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u17.png"}},
{
          "id":"61a56223604842858ca6d3a0eba07d7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":69,
              "y":614},
            "size":{
              "width":678,
              "height":343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a004faa3879b4bce8299a0ef190b4fe2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":69,
                  "y":614},
                "size":{
                  "width":678,
                  "height":343}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u19.png"}},
{
          "id":"ba7ed5d9a8024bcf8817170be923c927",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":413,
              "y":632},
            "size":{
              "width":312,
              "height":143}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55cdf1757b9a4d97ab826abee1cdf760",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":413,
                  "y":632},
                "size":{
                  "width":312,
                  "height":143}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u21.png"}},
{
          "id":"b85cf06bd028487ab82eb7de3e5e4114",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":413,
              "y":792},
            "size":{
              "width":312,
              "height":155}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07440b2644544841abf11c5ee02b2e77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":413,
                  "y":792},
                "size":{
                  "width":312,
                  "height":155}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u23.png"}},
{
          "id":"a85d78b82c8a4d32b473bd48b253f746",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":84,
              "y":430},
            "size":{
              "width":150,
              "height":22},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3dedd2feeb6d4992ab168191a237e493",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":84,
                  "y":430},
                "size":{
                  "width":150,
                  "height":22},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8a95aea6d11c42af9f7e3d4279d1085a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"bold",
            "location":{
              "x":308,
              "y":430},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"043eb16d82b14aa1b04473ddb2bb5297",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"bold",
                "location":{
                  "x":308,
                  "y":430},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open News in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"news.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b52c424feb9b4adaa16b90106c40f393",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":175,
              "y":109},
            "size":{
              "width":23,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1997f01a7104440e9e036d483bcbfa84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":175,
                  "y":109},
                "size":{
                  "width":23,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC0000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u29.png"}},
{
          "id":"f497e6dee6a94a678b6c4f9564e5a1bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":485,
              "y":205},
            "size":{
              "width":68,
              "height":22},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec65db959bae4fea853b7c78569370eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":485,
                  "y":205},
                "size":{
                  "width":68,
                  "height":22},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d26431867f4a40cb9172e4712a5d5ae1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":308,
              "y":456},
            "size":{
              "width":279,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27e7e49bf3b943c7b7c2ae372b44722d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":308,
                  "y":456},
                "size":{
                  "width":279,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open News Page template in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"news_page_template.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c3fd965815d4568a9e9e03e9d13fbd4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":308,
              "y":488},
            "size":{
              "width":237,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9be7e28c8f74eac8a04db7d3fc0290d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":308,
                  "y":488},
                "size":{
                  "width":237,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open News Page template in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"news_page_template.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eeca3a4394544dee9a6bfcb4f58ed2a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":84,
              "y":459},
            "size":{
              "width":199,
              "height":32},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"723d7c6972e442d3a8ad526674fcfc79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":84,
                  "y":459},
                "size":{
                  "width":199,
                  "height":32},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d1123de480b4e41b87df42902236d69",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":84,
              "y":501},
            "size":{
              "width":150,
              "height":48},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d486052bfd524bb6ba7358db79ca2c74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":84,
                  "y":501},
                "size":{
                  "width":150,
                  "height":48},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ca4ebd8f79f34428b42f43ae7b683a63",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":308,
              "y":521},
            "size":{
              "width":237,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e46225677d4149b99c73135a0740b5b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":308,
                  "y":521},
                "size":{
                  "width":237,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open News Page template in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"news_page_template.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"47ededfcd56e4dd88de88de515c12720",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":69,
              "y":199},
            "size":{
              "width":211,
              "height":212},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84f73635010342a58d7c1393865b2e09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":69,
                  "y":199},
                "size":{
                  "width":211,
                  "height":212},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"92fe7096669b4b54925c3fb261e7cc9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":691,
              "y":558},
            "size":{
              "width":34,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec66c2513f4143178342c5561c12da0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":691,
                  "y":558},
                "size":{
                  "width":34,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open News in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"news.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"39d066bd5be143fe86df114177f520b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":428,
              "y":802},
            "size":{
              "width":238,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea7e6671a77a49c7a50faa0e0e5fde08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":428,
                  "y":802},
                "size":{
                  "width":238,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f27028c955b4881ba6d21236ef75962",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":428,
              "y":836},
            "size":{
              "width":226,
              "height":80},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c81a68eace914f969d2cc19c0e9068f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":428,
                  "y":836},
                "size":{
                  "width":226,
                  "height":80},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Document Page in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"document_page.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d07cb07019c4712b8dc47449e914957",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":84,
              "y":626},
            "size":{
              "width":231,
              "height":22},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b4aa11f3bc14175ab819ab71d80e5e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":84,
                  "y":626},
                "size":{
                  "width":231,
                  "height":22},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a48189872fc6400ba74226f1b971fddd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":84,
              "y":658},
            "size":{
              "width":83,
              "height":69},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e6c1ba582a54ec48486ab5e1c9ec634",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":84,
                  "y":658},
                "size":{
                  "width":83,
                  "height":69},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Portfolio in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"portfolio.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"44373d1a33154ee2970ac880ff49ed5f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":167,
              "y":658},
            "size":{
              "width":193,
              "height":138},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7759979e5b304049bc14213ff465cbf5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":167,
                  "y":658},
                "size":{
                  "width":193,
                  "height":138},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Portfolio in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"portfolio.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"e6393d7fd0c34210afe6556cf33906a5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":84,
              "y":727},
            "size":{
              "width":83,
              "height":69},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec0462cf40c74dfbbaf8dbf820ca2300",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":84,
                  "y":727},
                "size":{
                  "width":83,
                  "height":69},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Portfolio in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"portfolio.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"167e8dd774ae4f84bfa64ca3390b0ae8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":84,
              "y":796},
            "size":{
              "width":276,
              "height":145},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d099da13a87242df81dcf43c16538425",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":84,
                  "y":796},
                "size":{
                  "width":276,
                  "height":145},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Portfolio in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"portfolio.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u43.png"}},
{
          "id":"69b97c23eee54277a7d7c377d790a56d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":339,
              "y":237},
            "size":{
              "width":358,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57fb144969b1409db01a16206ec25b80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":339,
                  "y":237},
                "size":{
                  "width":358,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ace03290e3e4c7981df31c7e84783b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":339,
              "y":280},
            "size":{
              "width":358,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4330af05ff9e4d41af4ff9a96bebffa1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":339,
                  "y":280},
                "size":{
                  "width":358,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"44a27f852f5148a7a282c08be2437f6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":339,
              "y":319},
            "size":{
              "width":358,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85e62985ce0e4843bb0bd3060ba49689",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":339,
                  "y":319},
                "size":{
                  "width":358,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"192377a778aa4413a05410e232f80e1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":339,
              "y":357},
            "size":{
              "width":358,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19e9f1e01f6b4a64a71a3a8735da11e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":339,
                  "y":357},
                "size":{
                  "width":358,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6332e9efd25645cda812a7861dffe19e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":535,
              "y":976},
            "size":{
              "width":40,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"475ceb66d849429e915fd4c4e54aa85c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":535,
                  "y":976},
                "size":{
                  "width":40,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u69.png"}},
{
          "id":"5ef1ddb45afe4e119d047457b2cd12df",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":585,
              "y":976},
            "size":{
              "width":40,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24ab14bdeae64d1f828e61712aec7a15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":585,
                  "y":976},
                "size":{
                  "width":40,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u69.png"}},
{
          "id":"34f521cef4aa433b82f5fb802aa34b53",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":635,
              "y":976},
            "size":{
              "width":40,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ace6b19f919647fbbe41c724831cf8d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":635,
                  "y":976},
                "size":{
                  "width":40,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u69.png"}},
{
          "id":"f783a00e69584eab9b676402fd5728a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":685,
              "y":976},
            "size":{
              "width":40,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6124b64b3f74802a85b9f08bbb823cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":685,
                  "y":976},
                "size":{
                  "width":40,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u69.png"}},
{
          "id":"6acbf9b245b647918e38893b566a11a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "location":{
              "x":626,
              "y":926},
            "size":{
              "width":40,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5727ada4fe5c4d7f8dbd3dc103cf3215",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "location":{
                  "x":626,
                  "y":926},
                "size":{
                  "width":40,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"488ed3ed6c664fd68963c5a3e870d4ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":597,
              "y":13},
            "size":{
              "width":208,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b6bf06eb2ec463990d6cba0e384ba1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":597,
                  "y":13},
                "size":{
                  "width":208,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "345513e758cc4a9e902c8e10402b09fd":{
      "scriptId":"u0"},
    "8580fb800fa24dfa850379cfee8108ea":{
      "scriptId":"u1"},
    "eba8cd51a067435da12689193bb49f2b":{
      "scriptId":"u2"},
    "9634558bb9ab4557b8a71e9729d4fed9":{
      "scriptId":"u3"},
    "c699867337a04b9797162aa6ca61f636":{
      "scriptId":"u4"},
    "f0c71c7a6ff04861ab402e90f789f6e9":{
      "scriptId":"u5"},
    "00545dd83eca4f26b060cc6cfdbdc8ea":{
      "scriptId":"u6"},
    "47b1b31c5cf243ef8235bf7d0bdcb037":{
      "scriptId":"u7"},
    "b31dc9cefcd74fee8e1685934661a70c":{
      "scriptId":"u8"},
    "5f61d7d8de86409e969e551ffda75e4c":{
      "scriptId":"u9"},
    "e969514d3d2e49e291bb396108c60a31":{
      "scriptId":"u10"},
    "4d16ef71ff4c4a7ca7a13731a20c54de":{
      "scriptId":"u11"},
    "e680ed0aa91a400cb2248480523eb426":{
      "scriptId":"u12"},
    "3e2c9c7f401c43d0b308fc737da37465":{
      "scriptId":"u13"},
    "1835cba8cf5c438ea51f80f60e21776d":{
      "scriptId":"u14"},
    "a600022e7f7d4b9e92fa032624b72dce":{
      "scriptId":"u15"},
    "a37a3c54d14d4e8bbd2de8892d25a94a":{
      "scriptId":"u16"},
    "858169ee9bde4f9d9fa44e78d80e1aff":{
      "scriptId":"u17"},
    "7c7213cf79b34a7b9e2cd76b3a3f249a":{
      "scriptId":"u18"},
    "61a56223604842858ca6d3a0eba07d7e":{
      "scriptId":"u19"},
    "a004faa3879b4bce8299a0ef190b4fe2":{
      "scriptId":"u20"},
    "ba7ed5d9a8024bcf8817170be923c927":{
      "scriptId":"u21"},
    "55cdf1757b9a4d97ab826abee1cdf760":{
      "scriptId":"u22"},
    "b85cf06bd028487ab82eb7de3e5e4114":{
      "scriptId":"u23"},
    "07440b2644544841abf11c5ee02b2e77":{
      "scriptId":"u24"},
    "a85d78b82c8a4d32b473bd48b253f746":{
      "scriptId":"u25"},
    "3dedd2feeb6d4992ab168191a237e493":{
      "scriptId":"u26"},
    "8a95aea6d11c42af9f7e3d4279d1085a":{
      "scriptId":"u27"},
    "043eb16d82b14aa1b04473ddb2bb5297":{
      "scriptId":"u28"},
    "b52c424feb9b4adaa16b90106c40f393":{
      "scriptId":"u29"},
    "1997f01a7104440e9e036d483bcbfa84":{
      "scriptId":"u30"},
    "f497e6dee6a94a678b6c4f9564e5a1bd":{
      "scriptId":"u31"},
    "ec65db959bae4fea853b7c78569370eb":{
      "scriptId":"u32"},
    "d26431867f4a40cb9172e4712a5d5ae1":{
      "scriptId":"u33"},
    "27e7e49bf3b943c7b7c2ae372b44722d":{
      "scriptId":"u34"},
    "2c3fd965815d4568a9e9e03e9d13fbd4":{
      "scriptId":"u35"},
    "d9be7e28c8f74eac8a04db7d3fc0290d":{
      "scriptId":"u36"},
    "eeca3a4394544dee9a6bfcb4f58ed2a1":{
      "scriptId":"u37"},
    "723d7c6972e442d3a8ad526674fcfc79":{
      "scriptId":"u38"},
    "8d1123de480b4e41b87df42902236d69":{
      "scriptId":"u39"},
    "d486052bfd524bb6ba7358db79ca2c74":{
      "scriptId":"u40"},
    "ca4ebd8f79f34428b42f43ae7b683a63":{
      "scriptId":"u41"},
    "e46225677d4149b99c73135a0740b5b5":{
      "scriptId":"u42"},
    "47ededfcd56e4dd88de88de515c12720":{
      "scriptId":"u43"},
    "84f73635010342a58d7c1393865b2e09":{
      "scriptId":"u44"},
    "92fe7096669b4b54925c3fb261e7cc9c":{
      "scriptId":"u45"},
    "ec66c2513f4143178342c5561c12da0b":{
      "scriptId":"u46"},
    "39d066bd5be143fe86df114177f520b7":{
      "scriptId":"u47"},
    "ea7e6671a77a49c7a50faa0e0e5fde08":{
      "scriptId":"u48"},
    "1f27028c955b4881ba6d21236ef75962":{
      "scriptId":"u49"},
    "c81a68eace914f969d2cc19c0e9068f6":{
      "scriptId":"u50"},
    "8d07cb07019c4712b8dc47449e914957":{
      "scriptId":"u51"},
    "8b4aa11f3bc14175ab819ab71d80e5e1":{
      "scriptId":"u52"},
    "a48189872fc6400ba74226f1b971fddd":{
      "scriptId":"u53"},
    "5e6c1ba582a54ec48486ab5e1c9ec634":{
      "scriptId":"u54"},
    "44373d1a33154ee2970ac880ff49ed5f":{
      "scriptId":"u55"},
    "7759979e5b304049bc14213ff465cbf5":{
      "scriptId":"u56"},
    "e6393d7fd0c34210afe6556cf33906a5":{
      "scriptId":"u57"},
    "ec0462cf40c74dfbbaf8dbf820ca2300":{
      "scriptId":"u58"},
    "167e8dd774ae4f84bfa64ca3390b0ae8":{
      "scriptId":"u59"},
    "d099da13a87242df81dcf43c16538425":{
      "scriptId":"u60"},
    "69b97c23eee54277a7d7c377d790a56d":{
      "scriptId":"u61"},
    "57fb144969b1409db01a16206ec25b80":{
      "scriptId":"u62"},
    "2ace03290e3e4c7981df31c7e84783b9":{
      "scriptId":"u63"},
    "4330af05ff9e4d41af4ff9a96bebffa1":{
      "scriptId":"u64"},
    "44a27f852f5148a7a282c08be2437f6b":{
      "scriptId":"u65"},
    "85e62985ce0e4843bb0bd3060ba49689":{
      "scriptId":"u66"},
    "192377a778aa4413a05410e232f80e1b":{
      "scriptId":"u67"},
    "19e9f1e01f6b4a64a71a3a8735da11e4":{
      "scriptId":"u68"},
    "6332e9efd25645cda812a7861dffe19e":{
      "scriptId":"u69"},
    "475ceb66d849429e915fd4c4e54aa85c":{
      "scriptId":"u70"},
    "5ef1ddb45afe4e119d047457b2cd12df":{
      "scriptId":"u71"},
    "24ab14bdeae64d1f828e61712aec7a15":{
      "scriptId":"u72"},
    "34f521cef4aa433b82f5fb802aa34b53":{
      "scriptId":"u73"},
    "ace6b19f919647fbbe41c724831cf8d7":{
      "scriptId":"u74"},
    "f783a00e69584eab9b676402fd5728a5":{
      "scriptId":"u75"},
    "f6124b64b3f74802a85b9f08bbb823cf":{
      "scriptId":"u76"},
    "6acbf9b245b647918e38893b566a11a9":{
      "scriptId":"u77"},
    "5727ada4fe5c4d7f8dbd3dc103cf3215":{
      "scriptId":"u78"},
    "488ed3ed6c664fd68963c5a3e870d4ae":{
      "scriptId":"u79"},
    "7b6bf06eb2ec463990d6cba0e384ba1b":{
      "scriptId":"u80"}}});